// Code generated by locale_generate.go from Qt 5.13. DO NOT EDIT.
package qrc

// Language is a language supported by Qt (note: multiple names can have the
// same code).
type Language uint16

const (
	LanguageAbkhazian                 Language = 2
	LanguageAfan                      Language = LanguageOromo
	LanguageAfar                      Language = 4
	LanguageAfrikaans                 Language = 5
	LanguageAghem                     Language = 237
	LanguageAhom                      Language = 340
	LanguageAkan                      Language = 146
	LanguageAkkadian                  Language = 262
	LanguageAkoose                    Language = 312
	LanguageAlbanian                  Language = 6
	LanguageAmericanSignLanguage      Language = 341
	LanguageAmharic                   Language = 7
	LanguageAncientEgyptian           Language = 263
	LanguageAncientGreek              Language = 264
	LanguageAncientNorthArabian       Language = 331
	LanguageAnyLanguage               Language = 0
	LanguageArabic                    Language = 8
	LanguageAragonese                 Language = 261
	LanguageAramaic                   Language = 265
	LanguageArdhamagadhiPrakrit       Language = 342
	LanguageArmenian                  Language = 9
	LanguageAssamese                  Language = 10
	LanguageAsturian                  Language = 256
	LanguageAsu                       Language = 205
	LanguageAtsam                     Language = 156
	LanguageAvaric                    Language = 216
	LanguageAvestan                   Language = 255
	LanguageAymara                    Language = 11
	LanguageAzerbaijani               Language = 12
	LanguageBafia                     Language = 243
	LanguageBalinese                  Language = 266
	LanguageBambara                   Language = 188
	LanguageBamun                     Language = 267
	LanguageBasaa                     Language = 238
	LanguageBashkir                   Language = 13
	LanguageBasque                    Language = 14
	LanguageBassa                     Language = 336
	LanguageBatakToba                 Language = 268
	LanguageBelarusian                Language = 22
	LanguageBemba                     Language = 195
	LanguageBena                      Language = 186
	LanguageBengali                   Language = 15
	LanguageBhojpuri                  Language = 343
	LanguageBhutani                   Language = LanguageDzongkha
	LanguageBihari                    Language = 17
	LanguageBislama                   Language = 18
	LanguageBlin                      Language = 152
	LanguageBodo                      Language = 215
	LanguageBosnian                   Language = 142
	LanguageBreton                    Language = 19
	LanguageBuginese                  Language = 269
	LanguageBuhid                     Language = 270
	LanguageBulgarian                 Language = 20
	LanguageBurmese                   Language = 21
	LanguageByelorussian              Language = LanguageBelarusian
	LanguageC                         Language = 1
	LanguageCambodian                 Language = LanguageKhmer
	LanguageCantonese                 Language = 357
	LanguageCarian                    Language = 271
	LanguageCatalan                   Language = 24
	LanguageCentralKurdish            Language = 316
	LanguageCentralMoroccoTamazight   Language = 212
	LanguageChakma                    Language = 272
	LanguageChamorro                  Language = 217
	LanguageChechen                   Language = 218
	LanguageCherokee                  Language = 190
	LanguageChewa                     Language = LanguageNyanja
	LanguageChiga                     Language = 211
	LanguageChinese                   Language = 25
	LanguageChurch                    Language = 219
	LanguageChuvash                   Language = 220
	LanguageClassicalMandaic          Language = 273
	LanguageColognian                 Language = 201
	LanguageCongoSwahili              Language = 250
	LanguageCoptic                    Language = 274
	LanguageCornish                   Language = 145
	LanguageCorsican                  Language = 26
	LanguageCree                      Language = 221
	LanguageCroatian                  Language = 27
	LanguageCzech                     Language = 28
	LanguageDanish                    Language = 29
	LanguageDivehi                    Language = 143
	LanguageDogri                     Language = 275
	LanguageDuala                     Language = 240
	LanguageDutch                     Language = 30
	LanguageDzongkha                  Language = 16
	LanguageEasternCham               Language = 276
	LanguageEasternKayah              Language = 277
	LanguageEmbu                      Language = 189
	LanguageEnglish                   Language = 31
	LanguageEsperanto                 Language = 32
	LanguageEstonian                  Language = 33
	LanguageEtruscan                  Language = 278
	LanguageEwe                       Language = 161
	LanguageEwondo                    Language = 242
	LanguageFaroese                   Language = 34
	LanguageFijian                    Language = 35
	LanguageFilipino                  Language = 166
	LanguageFinnish                   Language = 36
	LanguageFrench                    Language = 37
	LanguageFrisian                   Language = LanguageWesternFrisian
	LanguageFriulian                  Language = 159
	LanguageFulah                     Language = 177
	LanguageGa                        Language = 148
	LanguageGaelic                    Language = 39
	LanguageGalician                  Language = 40
	LanguageGanda                     Language = 194
	LanguageGeez                      Language = 153
	LanguageGeorgian                  Language = 41
	LanguageGerman                    Language = 42
	LanguageGothic                    Language = 279
	LanguageGreek                     Language = 43
	LanguageGreenlandic               Language = 44
	LanguageGuarani                   Language = 45
	LanguageGujarati                  Language = 46
	LanguageGusii                     Language = 175
	LanguageHaitian                   Language = 222
	LanguageHanunoo                   Language = 280
	LanguageHausa                     Language = 47
	LanguageHawaiian                  Language = 163
	LanguageHebrew                    Language = 48
	LanguageHerero                    Language = 223
	LanguageHieroglyphicLuwian        Language = 344
	LanguageHindi                     Language = 49
	LanguageHiriMotu                  Language = 224
	LanguageHmongNjua                 Language = 333
	LanguageHo                        Language = 334
	LanguageHungarian                 Language = 50
	LanguageIcelandic                 Language = 51
	LanguageIdo                       Language = 360
	LanguageIgbo                      Language = 149
	LanguageInariSami                 Language = 326
	LanguageIndonesian                Language = 52
	LanguageIngush                    Language = 281
	LanguageInterlingua               Language = 53
	LanguageInterlingue               Language = 54
	LanguageInuktitut                 Language = 55
	LanguageInupiak                   Language = 56
	LanguageIrish                     Language = 57
	LanguageItalian                   Language = 58
	LanguageJapanese                  Language = 59
	LanguageJavanese                  Language = 60
	LanguageJju                       Language = 158
	LanguageJolaFonyi                 Language = 241
	LanguageKabuverdianu              Language = 196
	LanguageKabyle                    Language = 184
	LanguageKako                      Language = 258
	LanguageKalenjin                  Language = 198
	LanguageKamba                     Language = 150
	LanguageKannada                   Language = 61
	LanguageKanuri                    Language = 225
	LanguageKashmiri                  Language = 62
	LanguageKazakh                    Language = 63
	LanguageKenyang                   Language = 319
	LanguageKhmer                     Language = 23
	LanguageKiche                     Language = 323
	LanguageKikuyu                    Language = 178
	LanguageKinyarwanda               Language = 64
	LanguageKirghiz                   Language = 65
	LanguageKomi                      Language = 226
	LanguageKongo                     Language = 227
	LanguageKonkani                   Language = 147
	LanguageKorean                    Language = 66
	LanguageKoro                      Language = 154
	LanguageKoyraChiini               Language = 208
	LanguageKoyraboroSenni            Language = 213
	LanguageKpelle                    Language = 169
	LanguageKurdish                   Language = 67
	LanguageKurundi                   Language = LanguageRundi
	LanguageKwanyama                  Language = 228
	LanguageKwasio                    Language = 246
	LanguageLakota                    Language = 313
	LanguageLangi                     Language = 193
	LanguageLao                       Language = 69
	LanguageLargeFloweryMiao          Language = 282
	LanguageLastLanguage              Language = LanguageWesternBalochi
	LanguageLatin                     Language = 70
	LanguageLatvian                   Language = 71
	LanguageLepcha                    Language = 283
	LanguageLezghian                  Language = 335
	LanguageLimbu                     Language = 284
	LanguageLimburgish                Language = 229
	LanguageLinearA                   Language = 332
	LanguageLingala                   Language = 72
	LanguageLisu                      Language = 285
	LanguageLiteraryChinese           Language = 345
	LanguageLithuanian                Language = 73
	LanguageLojban                    Language = 361
	LanguageLowGerman                 Language = 170
	LanguageLowerSorbian              Language = 317
	LanguageLu                        Language = 286
	LanguageLubaKatanga               Language = 230
	LanguageLuleSami                  Language = 325
	LanguageLuo                       Language = 210
	LanguageLuxembourgish             Language = 231
	LanguageLuyia                     Language = 204
	LanguageLycian                    Language = 287
	LanguageLydian                    Language = 288
	LanguageMacedonian                Language = 74
	LanguageMachame                   Language = 200
	LanguageMaithili                  Language = 339
	LanguageMakhuwaMeetto             Language = 244
	LanguageMakonde                   Language = 192
	LanguageMalagasy                  Language = 75
	LanguageMalay                     Language = 76
	LanguageMalayalam                 Language = 77
	LanguageMaltese                   Language = 78
	LanguageMandingo                  Language = 289
	LanguageManichaeanMiddlePersian   Language = 329
	LanguageManipuri                  Language = 290
	LanguageManx                      Language = 144
	LanguageMaori                     Language = 79
	LanguageMapuche                   Language = 315
	LanguageMarathi                   Language = 80
	LanguageMarshallese               Language = 81
	LanguageMasai                     Language = 202
	LanguageMazanderani               Language = 346
	LanguageMende                     Language = 330
	LanguageMeroitic                  Language = 291
	LanguageMeru                      Language = 197
	LanguageMeta                      Language = 259
	LanguageMohawk                    Language = 320
	LanguageMoldavian                 Language = LanguageRomanian
	LanguageMongolian                 Language = 82
	LanguageMono                      Language = 337
	LanguageMorisyen                  Language = 191
	LanguageMru                       Language = 347
	LanguageMundang                   Language = 245
	LanguageNama                      Language = 199
	LanguageNauruLanguage             Language = 83
	LanguageNavaho                    Language = 232
	LanguageNdonga                    Language = 233
	LanguageNepali                    Language = 84
	LanguageNewari                    Language = 348
	LanguageNgiemboon                 Language = 260
	LanguageNgomba                    Language = 257
	LanguageNko                       Language = 321
	LanguageNorthNdebele              Language = 181
	LanguageNorthernLuri              Language = 349
	LanguageNorthernSami              Language = 173
	LanguageNorthernSotho             Language = 172
	LanguageNorthernThai              Language = 292
	LanguageNorwegian                 Language = LanguageNorwegianBokmal
	LanguageNorwegianBokmal           Language = 85
	LanguageNorwegianNynorsk          Language = 141
	LanguageNuer                      Language = 247
	LanguageNyanja                    Language = 165
	LanguageNyankole                  Language = 185
	LanguageOccitan                   Language = 86
	LanguageOjibwa                    Language = 234
	LanguageOldIrish                  Language = 293
	LanguageOldNorse                  Language = 294
	LanguageOldPersian                Language = 295
	LanguageOldTurkish                Language = 296
	LanguageOriya                     Language = 87
	LanguageOromo                     Language = 3
	LanguageOsage                     Language = 358
	LanguageOssetic                   Language = 101
	LanguagePahlavi                   Language = 297
	LanguagePalauan                   Language = 350
	LanguagePali                      Language = 235
	LanguagePapiamento                Language = 351
	LanguageParthian                  Language = 298
	LanguagePashto                    Language = 88
	LanguagePersian                   Language = 89
	LanguagePhoenician                Language = 299
	LanguagePolish                    Language = 90
	LanguagePortuguese                Language = 91
	LanguagePrakritLanguage           Language = 300
	LanguagePrussian                  Language = 322
	LanguagePunjabi                   Language = 92
	LanguageQuechua                   Language = 93
	LanguageRejang                    Language = 301
	LanguageRhaetoRomance             Language = LanguageRomansh
	LanguageRomanian                  Language = 95
	LanguageRomansh                   Language = 94
	LanguageRombo                     Language = 182
	LanguageRundi                     Language = 68
	LanguageRussian                   Language = 96
	LanguageRwa                       Language = 209
	LanguageSabaean                   Language = 302
	LanguageSaho                      Language = 207
	LanguageSakha                     Language = 248
	LanguageSamaritan                 Language = 303
	LanguageSamburu                   Language = 179
	LanguageSamoan                    Language = 97
	LanguageSango                     Language = 98
	LanguageSangu                     Language = 249
	LanguageSanskrit                  Language = 99
	LanguageSantali                   Language = 304
	LanguageSaraiki                   Language = 352
	LanguageSardinian                 Language = 115
	LanguageSaurashtra                Language = 305
	LanguageSena                      Language = 180
	LanguageSerbian                   Language = 100
	LanguageSerboCroatian             Language = LanguageSerbian
	LanguageShambala                  Language = 214
	LanguageShona                     Language = 104
	LanguageSichuanYi                 Language = 168
	LanguageSicilian                  Language = 362
	LanguageSidamo                    Language = 155
	LanguageSindhi                    Language = 105
	LanguageSinhala                   Language = 106
	LanguageSkoltSami                 Language = 327
	LanguageSlovak                    Language = 108
	LanguageSlovenian                 Language = 109
	LanguageSoga                      Language = 203
	LanguageSomali                    Language = 110
	LanguageSora                      Language = 306
	LanguageSouthNdebele              Language = 171
	LanguageSouthernKurdish           Language = 363
	LanguageSouthernSami              Language = 324
	LanguageSouthernSotho             Language = 102
	LanguageSpanish                   Language = 111
	LanguageStandardMoroccanTamazight Language = 314
	LanguageSundanese                 Language = 112
	LanguageSwahili                   Language = 113
	LanguageSwati                     Language = 107
	LanguageSwedish                   Language = 114
	LanguageSwissGerman               Language = 167
	LanguageSylheti                   Language = 307
	LanguageSyriac                    Language = 151
	LanguageTachelhit                 Language = 183
	LanguageTagalog                   Language = LanguageFilipino
	LanguageTagbanwa                  Language = 308
	LanguageTahitian                  Language = 127
	LanguageTaiDam                    Language = 309
	LanguageTaiNua                    Language = 310
	LanguageTaita                     Language = 176
	LanguageTajik                     Language = 116
	LanguageTamil                     Language = 117
	LanguageTangut                    Language = 359
	LanguageTaroko                    Language = 174
	LanguageTasawaq                   Language = 251
	LanguageTatar                     Language = 118
	LanguageTedimChin                 Language = 338
	LanguageTelugu                    Language = 119
	LanguageTeso                      Language = 206
	LanguageThai                      Language = 120
	LanguageTibetan                   Language = 121
	LanguageTigre                     Language = 157
	LanguageTigrinya                  Language = 122
	LanguageTokPisin                  Language = 354
	LanguageTokelauLanguage           Language = 353
	LanguageTongan                    Language = 123
	LanguageTsonga                    Language = 124
	LanguageTswana                    Language = 103
	LanguageTurkish                   Language = 125
	LanguageTurkmen                   Language = 126
	LanguageTuvaluLanguage            Language = 355
	LanguageTwi                       Language = LanguageAkan
	LanguageTyap                      Language = 164
	LanguageUgaritic                  Language = 311
	LanguageUighur                    Language = 128
	LanguageUigur                     Language = LanguageUighur
	LanguageUkrainian                 Language = 129
	LanguageUncodedLanguages          Language = 356
	LanguageUpperSorbian              Language = 318
	LanguageUrdu                      Language = 130
	LanguageUzbek                     Language = 131
	LanguageVai                       Language = 252
	LanguageVenda                     Language = 160
	LanguageVietnamese                Language = 132
	LanguageVolapuk                   Language = 133
	LanguageVunjo                     Language = 187
	LanguageWalamo                    Language = 162
	LanguageWalloon                   Language = 236
	LanguageWalser                    Language = 253
	LanguageWarlpiri                  Language = 328
	LanguageWelsh                     Language = 134
	LanguageWesternBalochi            Language = 364
	LanguageWesternFrisian            Language = 38
	LanguageWolof                     Language = 135
	LanguageXhosa                     Language = 136
	LanguageYangben                   Language = 254
	LanguageYiddish                   Language = 137
	LanguageYoruba                    Language = 138
	LanguageZarma                     Language = 239
	LanguageZhuang                    Language = 139
	LanguageZulu                      Language = 140
)

func (l Language) String() string {
	switch l {
	case 0:
		return "AnyLanguage"
	case 1:
		return "C"
	case 2:
		return "Abkhazian"
	case 3:
		return "Oromo" // Afan
	case 4:
		return "Afar"
	case 5:
		return "Afrikaans"
	case 6:
		return "Albanian"
	case 7:
		return "Amharic"
	case 8:
		return "Arabic"
	case 9:
		return "Armenian"
	case 10:
		return "Assamese"
	case 11:
		return "Aymara"
	case 12:
		return "Azerbaijani"
	case 13:
		return "Bashkir"
	case 14:
		return "Basque"
	case 15:
		return "Bengali"
	case 16:
		return "Dzongkha" // Bhutani
	case 17:
		return "Bihari"
	case 18:
		return "Bislama"
	case 19:
		return "Breton"
	case 20:
		return "Bulgarian"
	case 21:
		return "Burmese"
	case 22:
		return "Belarusian" // Byelorussian
	case 23:
		return "Khmer" // Cambodian
	case 24:
		return "Catalan"
	case 25:
		return "Chinese"
	case 26:
		return "Corsican"
	case 27:
		return "Croatian"
	case 28:
		return "Czech"
	case 29:
		return "Danish"
	case 30:
		return "Dutch"
	case 31:
		return "English"
	case 32:
		return "Esperanto"
	case 33:
		return "Estonian"
	case 34:
		return "Faroese"
	case 35:
		return "Fijian"
	case 36:
		return "Finnish"
	case 37:
		return "French"
	case 38:
		return "WesternFrisian" // Frisian
	case 39:
		return "Gaelic"
	case 40:
		return "Galician"
	case 41:
		return "Georgian"
	case 42:
		return "German"
	case 43:
		return "Greek"
	case 44:
		return "Greenlandic"
	case 45:
		return "Guarani"
	case 46:
		return "Gujarati"
	case 47:
		return "Hausa"
	case 48:
		return "Hebrew"
	case 49:
		return "Hindi"
	case 50:
		return "Hungarian"
	case 51:
		return "Icelandic"
	case 52:
		return "Indonesian"
	case 53:
		return "Interlingua"
	case 54:
		return "Interlingue"
	case 55:
		return "Inuktitut"
	case 56:
		return "Inupiak"
	case 57:
		return "Irish"
	case 58:
		return "Italian"
	case 59:
		return "Japanese"
	case 60:
		return "Javanese"
	case 61:
		return "Kannada"
	case 62:
		return "Kashmiri"
	case 63:
		return "Kazakh"
	case 64:
		return "Kinyarwanda"
	case 65:
		return "Kirghiz"
	case 66:
		return "Korean"
	case 67:
		return "Kurdish"
	case 68:
		return "Rundi" // Kurundi
	case 69:
		return "Lao"
	case 70:
		return "Latin"
	case 71:
		return "Latvian"
	case 72:
		return "Lingala"
	case 73:
		return "Lithuanian"
	case 74:
		return "Macedonian"
	case 75:
		return "Malagasy"
	case 76:
		return "Malay"
	case 77:
		return "Malayalam"
	case 78:
		return "Maltese"
	case 79:
		return "Maori"
	case 80:
		return "Marathi"
	case 81:
		return "Marshallese"
	case 82:
		return "Mongolian"
	case 83:
		return "NauruLanguage"
	case 84:
		return "Nepali"
	case 85:
		return "NorwegianBokmal" // Norwegian
	case 86:
		return "Occitan"
	case 87:
		return "Oriya"
	case 88:
		return "Pashto"
	case 89:
		return "Persian"
	case 90:
		return "Polish"
	case 91:
		return "Portuguese"
	case 92:
		return "Punjabi"
	case 93:
		return "Quechua"
	case 94:
		return "Romansh" // RhaetoRomance
	case 95:
		return "Romanian" // Moldavian
	case 96:
		return "Russian"
	case 97:
		return "Samoan"
	case 98:
		return "Sango"
	case 99:
		return "Sanskrit"
	case 100:
		return "Serbian" // SerboCroatian
	case 101:
		return "Ossetic"
	case 102:
		return "SouthernSotho"
	case 103:
		return "Tswana"
	case 104:
		return "Shona"
	case 105:
		return "Sindhi"
	case 106:
		return "Sinhala"
	case 107:
		return "Swati"
	case 108:
		return "Slovak"
	case 109:
		return "Slovenian"
	case 110:
		return "Somali"
	case 111:
		return "Spanish"
	case 112:
		return "Sundanese"
	case 113:
		return "Swahili"
	case 114:
		return "Swedish"
	case 115:
		return "Sardinian"
	case 116:
		return "Tajik"
	case 117:
		return "Tamil"
	case 118:
		return "Tatar"
	case 119:
		return "Telugu"
	case 120:
		return "Thai"
	case 121:
		return "Tibetan"
	case 122:
		return "Tigrinya"
	case 123:
		return "Tongan"
	case 124:
		return "Tsonga"
	case 125:
		return "Turkish"
	case 126:
		return "Turkmen"
	case 127:
		return "Tahitian"
	case 128:
		return "Uighur" // Uigur
	case 129:
		return "Ukrainian"
	case 130:
		return "Urdu"
	case 131:
		return "Uzbek"
	case 132:
		return "Vietnamese"
	case 133:
		return "Volapuk"
	case 134:
		return "Welsh"
	case 135:
		return "Wolof"
	case 136:
		return "Xhosa"
	case 137:
		return "Yiddish"
	case 138:
		return "Yoruba"
	case 139:
		return "Zhuang"
	case 140:
		return "Zulu"
	case 141:
		return "NorwegianNynorsk"
	case 142:
		return "Bosnian"
	case 143:
		return "Divehi"
	case 144:
		return "Manx"
	case 145:
		return "Cornish"
	case 146:
		return "Akan" // Twi
	case 147:
		return "Konkani"
	case 148:
		return "Ga"
	case 149:
		return "Igbo"
	case 150:
		return "Kamba"
	case 151:
		return "Syriac"
	case 152:
		return "Blin"
	case 153:
		return "Geez"
	case 154:
		return "Koro"
	case 155:
		return "Sidamo"
	case 156:
		return "Atsam"
	case 157:
		return "Tigre"
	case 158:
		return "Jju"
	case 159:
		return "Friulian"
	case 160:
		return "Venda"
	case 161:
		return "Ewe"
	case 162:
		return "Walamo"
	case 163:
		return "Hawaiian"
	case 164:
		return "Tyap"
	case 165:
		return "Nyanja" // Chewa
	case 166:
		return "Filipino" // Tagalog
	case 167:
		return "SwissGerman"
	case 168:
		return "SichuanYi"
	case 169:
		return "Kpelle"
	case 170:
		return "LowGerman"
	case 171:
		return "SouthNdebele"
	case 172:
		return "NorthernSotho"
	case 173:
		return "NorthernSami"
	case 174:
		return "Taroko"
	case 175:
		return "Gusii"
	case 176:
		return "Taita"
	case 177:
		return "Fulah"
	case 178:
		return "Kikuyu"
	case 179:
		return "Samburu"
	case 180:
		return "Sena"
	case 181:
		return "NorthNdebele"
	case 182:
		return "Rombo"
	case 183:
		return "Tachelhit"
	case 184:
		return "Kabyle"
	case 185:
		return "Nyankole"
	case 186:
		return "Bena"
	case 187:
		return "Vunjo"
	case 188:
		return "Bambara"
	case 189:
		return "Embu"
	case 190:
		return "Cherokee"
	case 191:
		return "Morisyen"
	case 192:
		return "Makonde"
	case 193:
		return "Langi"
	case 194:
		return "Ganda"
	case 195:
		return "Bemba"
	case 196:
		return "Kabuverdianu"
	case 197:
		return "Meru"
	case 198:
		return "Kalenjin"
	case 199:
		return "Nama"
	case 200:
		return "Machame"
	case 201:
		return "Colognian"
	case 202:
		return "Masai"
	case 203:
		return "Soga"
	case 204:
		return "Luyia"
	case 205:
		return "Asu"
	case 206:
		return "Teso"
	case 207:
		return "Saho"
	case 208:
		return "KoyraChiini"
	case 209:
		return "Rwa"
	case 210:
		return "Luo"
	case 211:
		return "Chiga"
	case 212:
		return "CentralMoroccoTamazight"
	case 213:
		return "KoyraboroSenni"
	case 214:
		return "Shambala"
	case 215:
		return "Bodo"
	case 216:
		return "Avaric"
	case 217:
		return "Chamorro"
	case 218:
		return "Chechen"
	case 219:
		return "Church"
	case 220:
		return "Chuvash"
	case 221:
		return "Cree"
	case 222:
		return "Haitian"
	case 223:
		return "Herero"
	case 224:
		return "HiriMotu"
	case 225:
		return "Kanuri"
	case 226:
		return "Komi"
	case 227:
		return "Kongo"
	case 228:
		return "Kwanyama"
	case 229:
		return "Limburgish"
	case 230:
		return "LubaKatanga"
	case 231:
		return "Luxembourgish"
	case 232:
		return "Navaho"
	case 233:
		return "Ndonga"
	case 234:
		return "Ojibwa"
	case 235:
		return "Pali"
	case 236:
		return "Walloon"
	case 237:
		return "Aghem"
	case 238:
		return "Basaa"
	case 239:
		return "Zarma"
	case 240:
		return "Duala"
	case 241:
		return "JolaFonyi"
	case 242:
		return "Ewondo"
	case 243:
		return "Bafia"
	case 244:
		return "MakhuwaMeetto"
	case 245:
		return "Mundang"
	case 246:
		return "Kwasio"
	case 247:
		return "Nuer"
	case 248:
		return "Sakha"
	case 249:
		return "Sangu"
	case 250:
		return "CongoSwahili"
	case 251:
		return "Tasawaq"
	case 252:
		return "Vai"
	case 253:
		return "Walser"
	case 254:
		return "Yangben"
	case 255:
		return "Avestan"
	case 256:
		return "Asturian"
	case 257:
		return "Ngomba"
	case 258:
		return "Kako"
	case 259:
		return "Meta"
	case 260:
		return "Ngiemboon"
	case 261:
		return "Aragonese"
	case 262:
		return "Akkadian"
	case 263:
		return "AncientEgyptian"
	case 264:
		return "AncientGreek"
	case 265:
		return "Aramaic"
	case 266:
		return "Balinese"
	case 267:
		return "Bamun"
	case 268:
		return "BatakToba"
	case 269:
		return "Buginese"
	case 270:
		return "Buhid"
	case 271:
		return "Carian"
	case 272:
		return "Chakma"
	case 273:
		return "ClassicalMandaic"
	case 274:
		return "Coptic"
	case 275:
		return "Dogri"
	case 276:
		return "EasternCham"
	case 277:
		return "EasternKayah"
	case 278:
		return "Etruscan"
	case 279:
		return "Gothic"
	case 280:
		return "Hanunoo"
	case 281:
		return "Ingush"
	case 282:
		return "LargeFloweryMiao"
	case 283:
		return "Lepcha"
	case 284:
		return "Limbu"
	case 285:
		return "Lisu"
	case 286:
		return "Lu"
	case 287:
		return "Lycian"
	case 288:
		return "Lydian"
	case 289:
		return "Mandingo"
	case 290:
		return "Manipuri"
	case 291:
		return "Meroitic"
	case 292:
		return "NorthernThai"
	case 293:
		return "OldIrish"
	case 294:
		return "OldNorse"
	case 295:
		return "OldPersian"
	case 296:
		return "OldTurkish"
	case 297:
		return "Pahlavi"
	case 298:
		return "Parthian"
	case 299:
		return "Phoenician"
	case 300:
		return "PrakritLanguage"
	case 301:
		return "Rejang"
	case 302:
		return "Sabaean"
	case 303:
		return "Samaritan"
	case 304:
		return "Santali"
	case 305:
		return "Saurashtra"
	case 306:
		return "Sora"
	case 307:
		return "Sylheti"
	case 308:
		return "Tagbanwa"
	case 309:
		return "TaiDam"
	case 310:
		return "TaiNua"
	case 311:
		return "Ugaritic"
	case 312:
		return "Akoose"
	case 313:
		return "Lakota"
	case 314:
		return "StandardMoroccanTamazight"
	case 315:
		return "Mapuche"
	case 316:
		return "CentralKurdish"
	case 317:
		return "LowerSorbian"
	case 318:
		return "UpperSorbian"
	case 319:
		return "Kenyang"
	case 320:
		return "Mohawk"
	case 321:
		return "Nko"
	case 322:
		return "Prussian"
	case 323:
		return "Kiche"
	case 324:
		return "SouthernSami"
	case 325:
		return "LuleSami"
	case 326:
		return "InariSami"
	case 327:
		return "SkoltSami"
	case 328:
		return "Warlpiri"
	case 329:
		return "ManichaeanMiddlePersian"
	case 330:
		return "Mende"
	case 331:
		return "AncientNorthArabian"
	case 332:
		return "LinearA"
	case 333:
		return "HmongNjua"
	case 334:
		return "Ho"
	case 335:
		return "Lezghian"
	case 336:
		return "Bassa"
	case 337:
		return "Mono"
	case 338:
		return "TedimChin"
	case 339:
		return "Maithili"
	case 340:
		return "Ahom"
	case 341:
		return "AmericanSignLanguage"
	case 342:
		return "ArdhamagadhiPrakrit"
	case 343:
		return "Bhojpuri"
	case 344:
		return "HieroglyphicLuwian"
	case 345:
		return "LiteraryChinese"
	case 346:
		return "Mazanderani"
	case 347:
		return "Mru"
	case 348:
		return "Newari"
	case 349:
		return "NorthernLuri"
	case 350:
		return "Palauan"
	case 351:
		return "Papiamento"
	case 352:
		return "Saraiki"
	case 353:
		return "TokelauLanguage"
	case 354:
		return "TokPisin"
	case 355:
		return "TuvaluLanguage"
	case 356:
		return "UncodedLanguages"
	case 357:
		return "Cantonese"
	case 358:
		return "Osage"
	case 359:
		return "Tangut"
	case 360:
		return "Ido"
	case 361:
		return "Lojban"
	case 362:
		return "Sicilian"
	case 363:
		return "SouthernKurdish"
	case 364:
		return "WesternBalochi" // LastLanguage
	}
	panic("no such language")
}

// Country is a country supported by Qt (note: multiple names can have the same
// code).
type Country uint16

const (
	CountryAfghanistan                            Country = 1
	CountryAlandIslands                           Country = 248
	CountryAlbania                                Country = 2
	CountryAlgeria                                Country = 3
	CountryAmericanSamoa                          Country = 4
	CountryAndorra                                Country = 5
	CountryAngola                                 Country = 6
	CountryAnguilla                               Country = 7
	CountryAntarctica                             Country = 8
	CountryAntiguaAndBarbuda                      Country = 9
	CountryAnyCountry                             Country = 0
	CountryArgentina                              Country = 10
	CountryArmenia                                Country = 11
	CountryAruba                                  Country = 12
	CountryAscensionIsland                        Country = 247
	CountryAustralia                              Country = 13
	CountryAustria                                Country = 14
	CountryAzerbaijan                             Country = 15
	CountryBahamas                                Country = 16
	CountryBahrain                                Country = 17
	CountryBangladesh                             Country = 18
	CountryBarbados                               Country = 19
	CountryBelarus                                Country = 20
	CountryBelgium                                Country = 21
	CountryBelize                                 Country = 22
	CountryBenin                                  Country = 23
	CountryBermuda                                Country = 24
	CountryBhutan                                 Country = 25
	CountryBolivia                                Country = 26
	CountryBonaire                                Country = 255
	CountryBosniaAndHerzegowina                   Country = 27
	CountryBotswana                               Country = 28
	CountryBouvetIsland                           Country = 29
	CountryBrazil                                 Country = 30
	CountryBritishIndianOceanTerritory            Country = 31
	CountryBritishVirginIslands                   Country = 233
	CountryBrunei                                 Country = 32
	CountryBulgaria                               Country = 33
	CountryBurkinaFaso                            Country = 34
	CountryBurundi                                Country = 35
	CountryCambodia                               Country = 36
	CountryCameroon                               Country = 37
	CountryCanada                                 Country = 38
	CountryCanaryIslands                          Country = 238
	CountryCapeVerde                              Country = 39
	CountryCaymanIslands                          Country = 40
	CountryCentralAfricanRepublic                 Country = 41
	CountryCeutaAndMelilla                        Country = 250
	CountryChad                                   Country = 42
	CountryChile                                  Country = 43
	CountryChina                                  Country = 44
	CountryChristmasIsland                        Country = 45
	CountryClippertonIsland                       Country = 241
	CountryCocosIslands                           Country = 46
	CountryColombia                               Country = 47
	CountryComoros                                Country = 48
	CountryCongoBrazzaville                       Country = 50
	CountryCongoKinshasa                          Country = 49
	CountryCookIslands                            Country = 51
	CountryCostaRica                              Country = 52
	CountryCroatia                                Country = 54
	CountryCuba                                   Country = 55
	CountryCuraSao                                Country = 152
	CountryCyprus                                 Country = 56
	CountryCzechRepublic                          Country = 57
	CountryDemocraticRepublicOfCongo              Country = CountryCongoKinshasa
	CountryDemocraticRepublicOfKorea              Country = CountryNorthKorea
	CountryDenmark                                Country = 58
	CountryDiegoGarcia                            Country = 249
	CountryDjibouti                               Country = 59
	CountryDominica                               Country = 60
	CountryDominicanRepublic                      Country = 61
	CountryEastTimor                              Country = 62
	CountryEcuador                                Country = 63
	CountryEgypt                                  Country = 64
	CountryElSalvador                             Country = 65
	CountryEquatorialGuinea                       Country = 66
	CountryEritrea                                Country = 67
	CountryEstonia                                Country = 68
	CountryEthiopia                               Country = 69
	CountryEurope                                 Country = 261
	CountryEuropeanUnion                          Country = 258
	CountryFalklandIslands                        Country = 70
	CountryFaroeIslands                           Country = 71
	CountryFiji                                   Country = 72
	CountryFinland                                Country = 73
	CountryFrance                                 Country = 74
	CountryFrenchGuiana                           Country = 76
	CountryFrenchPolynesia                        Country = 77
	CountryFrenchSouthernTerritories              Country = 78
	CountryGabon                                  Country = 79
	CountryGambia                                 Country = 80
	CountryGeorgia                                Country = 81
	CountryGermany                                Country = 82
	CountryGhana                                  Country = 83
	CountryGibraltar                              Country = 84
	CountryGreece                                 Country = 85
	CountryGreenland                              Country = 86
	CountryGrenada                                Country = 87
	CountryGuadeloupe                             Country = 88
	CountryGuam                                   Country = 89
	CountryGuatemala                              Country = 90
	CountryGuernsey                               Country = 75
	CountryGuinea                                 Country = 91
	CountryGuineaBissau                           Country = 92
	CountryGuyana                                 Country = 93
	CountryHaiti                                  Country = 94
	CountryHeardAndMcDonaldIslands                Country = 95
	CountryHonduras                               Country = 96
	CountryHongKong                               Country = 97
	CountryHungary                                Country = 98
	CountryIceland                                Country = 99
	CountryIndia                                  Country = 100
	CountryIndonesia                              Country = 101
	CountryIran                                   Country = 102
	CountryIraq                                   Country = 103
	CountryIreland                                Country = 104
	CountryIsleOfMan                              Country = 251
	CountryIsrael                                 Country = 105
	CountryItaly                                  Country = 106
	CountryIvoryCoast                             Country = 53
	CountryJamaica                                Country = 107
	CountryJapan                                  Country = 108
	CountryJersey                                 Country = 252
	CountryJordan                                 Country = 109
	CountryKazakhstan                             Country = 110
	CountryKenya                                  Country = 111
	CountryKiribati                               Country = 112
	CountryKosovo                                 Country = 257
	CountryKuwait                                 Country = 115
	CountryKyrgyzstan                             Country = 116
	CountryLaos                                   Country = 117
	CountryLastCountry                            Country = CountryEurope
	CountryLatinAmerica                           Country = 246
	CountryLatinAmericaAndTheCaribbean            Country = CountryLatinAmerica
	CountryLatvia                                 Country = 118
	CountryLebanon                                Country = 119
	CountryLesotho                                Country = 120
	CountryLiberia                                Country = 121
	CountryLibya                                  Country = 122
	CountryLiechtenstein                          Country = 123
	CountryLithuania                              Country = 124
	CountryLuxembourg                             Country = 125
	CountryMacau                                  Country = 126
	CountryMacedonia                              Country = 127
	CountryMadagascar                             Country = 128
	CountryMalawi                                 Country = 129
	CountryMalaysia                               Country = 130
	CountryMaldives                               Country = 131
	CountryMali                                   Country = 132
	CountryMalta                                  Country = 133
	CountryMarshallIslands                        Country = 134
	CountryMartinique                             Country = 135
	CountryMauritania                             Country = 136
	CountryMauritius                              Country = 137
	CountryMayotte                                Country = 138
	CountryMexico                                 Country = 139
	CountryMicronesia                             Country = 140
	CountryMoldova                                Country = 141
	CountryMonaco                                 Country = 142
	CountryMongolia                               Country = 143
	CountryMontenegro                             Country = 242
	CountryMontserrat                             Country = 144
	CountryMorocco                                Country = 145
	CountryMozambique                             Country = 146
	CountryMyanmar                                Country = 147
	CountryNamibia                                Country = 148
	CountryNauruCountry                           Country = 149
	CountryNepal                                  Country = 150
	CountryNetherlands                            Country = 151
	CountryNewCaledonia                           Country = 153
	CountryNewZealand                             Country = 154
	CountryNicaragua                              Country = 155
	CountryNiger                                  Country = 156
	CountryNigeria                                Country = 157
	CountryNiue                                   Country = 158
	CountryNorfolkIsland                          Country = 159
	CountryNorthKorea                             Country = 113
	CountryNorthernMarianaIslands                 Country = 160
	CountryNorway                                 Country = 161
	CountryOman                                   Country = 162
	CountryOutlyingOceania                        Country = 259
	CountryPakistan                               Country = 163
	CountryPalau                                  Country = 164
	CountryPalestinianTerritories                 Country = 165
	CountryPanama                                 Country = 166
	CountryPapuaNewGuinea                         Country = 167
	CountryParaguay                               Country = 168
	CountryPeoplesRepublicOfCongo                 Country = CountryCongoBrazzaville
	CountryPeru                                   Country = 169
	CountryPhilippines                            Country = 170
	CountryPitcairn                               Country = 171
	CountryPoland                                 Country = 172
	CountryPortugal                               Country = 173
	CountryPuertoRico                             Country = 174
	CountryQatar                                  Country = 175
	CountryRepublicOfKorea                        Country = CountrySouthKorea
	CountryReunion                                Country = 176
	CountryRomania                                Country = 177
	CountryRussia                                 Country = 178
	CountryRussianFederation                      Country = CountryRussia
	CountryRwanda                                 Country = 179
	CountrySaintBarthelemy                        Country = 244
	CountrySaintHelena                            Country = 199
	CountrySaintKittsAndNevis                     Country = 180
	CountrySaintLucia                             Country = 181
	CountrySaintMartin                            Country = 245
	CountrySaintPierreAndMiquelon                 Country = 200
	CountrySaintVincentAndTheGrenadines           Country = 182
	CountrySamoa                                  Country = 183
	CountrySanMarino                              Country = 184
	CountrySaoTomeAndPrincipe                     Country = 185
	CountrySaudiArabia                            Country = 186
	CountrySenegal                                Country = 187
	CountrySerbia                                 Country = 243
	CountrySeychelles                             Country = 188
	CountrySierraLeone                            Country = 189
	CountrySingapore                              Country = 190
	CountrySintMaarten                            Country = 256
	CountrySlovakia                               Country = 191
	CountrySlovenia                               Country = 192
	CountrySolomonIslands                         Country = 193
	CountrySomalia                                Country = 194
	CountrySouthAfrica                            Country = 195
	CountrySouthGeorgiaAndTheSouthSandwichIslands Country = 196
	CountrySouthKorea                             Country = 114
	CountrySouthSudan                             Country = 254
	CountrySpain                                  Country = 197
	CountrySriLanka                               Country = 198
	CountrySudan                                  Country = 201
	CountrySuriname                               Country = 202
	CountrySvalbardAndJanMayenIslands             Country = 203
	CountrySwaziland                              Country = 204
	CountrySweden                                 Country = 205
	CountrySwitzerland                            Country = 206
	CountrySyria                                  Country = 207
	CountrySyrianArabRepublic                     Country = CountrySyria
	CountryTaiwan                                 Country = 208
	CountryTajikistan                             Country = 209
	CountryTanzania                               Country = 210
	CountryThailand                               Country = 211
	CountryTogo                                   Country = 212
	CountryTokelau                                Country = CountryTokelauCountry
	CountryTokelauCountry                         Country = 213
	CountryTonga                                  Country = 214
	CountryTrinidadAndTobago                      Country = 215
	CountryTristanDaCunha                         Country = 253
	CountryTunisia                                Country = 216
	CountryTurkey                                 Country = 217
	CountryTurkmenistan                           Country = 218
	CountryTurksAndCaicosIslands                  Country = 219
	CountryTuvalu                                 Country = CountryTuvaluCountry
	CountryTuvaluCountry                          Country = 220
	CountryUganda                                 Country = 221
	CountryUkraine                                Country = 222
	CountryUnitedArabEmirates                     Country = 223
	CountryUnitedKingdom                          Country = 224
	CountryUnitedStates                           Country = 225
	CountryUnitedStatesMinorOutlyingIslands       Country = 226
	CountryUnitedStatesVirginIslands              Country = 234
	CountryUruguay                                Country = 227
	CountryUzbekistan                             Country = 228
	CountryVanuatu                                Country = 229
	CountryVaticanCityState                       Country = 230
	CountryVenezuela                              Country = 231
	CountryVietnam                                Country = 232
	CountryWallisAndFutunaIslands                 Country = 235
	CountryWesternSahara                          Country = 236
	CountryWorld                                  Country = 260
	CountryYemen                                  Country = 237
	CountryZambia                                 Country = 239
	CountryZimbabwe                               Country = 240
)

func (c Country) String() string {
	switch c {
	case 0:
		return "AnyCountry"
	case 1:
		return "Afghanistan"
	case 2:
		return "Albania"
	case 3:
		return "Algeria"
	case 4:
		return "AmericanSamoa"
	case 5:
		return "Andorra"
	case 6:
		return "Angola"
	case 7:
		return "Anguilla"
	case 8:
		return "Antarctica"
	case 9:
		return "AntiguaAndBarbuda"
	case 10:
		return "Argentina"
	case 11:
		return "Armenia"
	case 12:
		return "Aruba"
	case 13:
		return "Australia"
	case 14:
		return "Austria"
	case 15:
		return "Azerbaijan"
	case 16:
		return "Bahamas"
	case 17:
		return "Bahrain"
	case 18:
		return "Bangladesh"
	case 19:
		return "Barbados"
	case 20:
		return "Belarus"
	case 21:
		return "Belgium"
	case 22:
		return "Belize"
	case 23:
		return "Benin"
	case 24:
		return "Bermuda"
	case 25:
		return "Bhutan"
	case 26:
		return "Bolivia"
	case 27:
		return "BosniaAndHerzegowina"
	case 28:
		return "Botswana"
	case 29:
		return "BouvetIsland"
	case 30:
		return "Brazil"
	case 31:
		return "BritishIndianOceanTerritory"
	case 32:
		return "Brunei"
	case 33:
		return "Bulgaria"
	case 34:
		return "BurkinaFaso"
	case 35:
		return "Burundi"
	case 36:
		return "Cambodia"
	case 37:
		return "Cameroon"
	case 38:
		return "Canada"
	case 39:
		return "CapeVerde"
	case 40:
		return "CaymanIslands"
	case 41:
		return "CentralAfricanRepublic"
	case 42:
		return "Chad"
	case 43:
		return "Chile"
	case 44:
		return "China"
	case 45:
		return "ChristmasIsland"
	case 46:
		return "CocosIslands"
	case 47:
		return "Colombia"
	case 48:
		return "Comoros"
	case 49:
		return "CongoKinshasa" // DemocraticRepublicOfCongo
	case 50:
		return "CongoBrazzaville" // PeoplesRepublicOfCongo
	case 51:
		return "CookIslands"
	case 52:
		return "CostaRica"
	case 53:
		return "IvoryCoast"
	case 54:
		return "Croatia"
	case 55:
		return "Cuba"
	case 56:
		return "Cyprus"
	case 57:
		return "CzechRepublic"
	case 58:
		return "Denmark"
	case 59:
		return "Djibouti"
	case 60:
		return "Dominica"
	case 61:
		return "DominicanRepublic"
	case 62:
		return "EastTimor"
	case 63:
		return "Ecuador"
	case 64:
		return "Egypt"
	case 65:
		return "ElSalvador"
	case 66:
		return "EquatorialGuinea"
	case 67:
		return "Eritrea"
	case 68:
		return "Estonia"
	case 69:
		return "Ethiopia"
	case 70:
		return "FalklandIslands"
	case 71:
		return "FaroeIslands"
	case 72:
		return "Fiji"
	case 73:
		return "Finland"
	case 74:
		return "France"
	case 75:
		return "Guernsey"
	case 76:
		return "FrenchGuiana"
	case 77:
		return "FrenchPolynesia"
	case 78:
		return "FrenchSouthernTerritories"
	case 79:
		return "Gabon"
	case 80:
		return "Gambia"
	case 81:
		return "Georgia"
	case 82:
		return "Germany"
	case 83:
		return "Ghana"
	case 84:
		return "Gibraltar"
	case 85:
		return "Greece"
	case 86:
		return "Greenland"
	case 87:
		return "Grenada"
	case 88:
		return "Guadeloupe"
	case 89:
		return "Guam"
	case 90:
		return "Guatemala"
	case 91:
		return "Guinea"
	case 92:
		return "GuineaBissau"
	case 93:
		return "Guyana"
	case 94:
		return "Haiti"
	case 95:
		return "HeardAndMcDonaldIslands"
	case 96:
		return "Honduras"
	case 97:
		return "HongKong"
	case 98:
		return "Hungary"
	case 99:
		return "Iceland"
	case 100:
		return "India"
	case 101:
		return "Indonesia"
	case 102:
		return "Iran"
	case 103:
		return "Iraq"
	case 104:
		return "Ireland"
	case 105:
		return "Israel"
	case 106:
		return "Italy"
	case 107:
		return "Jamaica"
	case 108:
		return "Japan"
	case 109:
		return "Jordan"
	case 110:
		return "Kazakhstan"
	case 111:
		return "Kenya"
	case 112:
		return "Kiribati"
	case 113:
		return "NorthKorea" // DemocraticRepublicOfKorea
	case 114:
		return "SouthKorea" // RepublicOfKorea
	case 115:
		return "Kuwait"
	case 116:
		return "Kyrgyzstan"
	case 117:
		return "Laos"
	case 118:
		return "Latvia"
	case 119:
		return "Lebanon"
	case 120:
		return "Lesotho"
	case 121:
		return "Liberia"
	case 122:
		return "Libya"
	case 123:
		return "Liechtenstein"
	case 124:
		return "Lithuania"
	case 125:
		return "Luxembourg"
	case 126:
		return "Macau"
	case 127:
		return "Macedonia"
	case 128:
		return "Madagascar"
	case 129:
		return "Malawi"
	case 130:
		return "Malaysia"
	case 131:
		return "Maldives"
	case 132:
		return "Mali"
	case 133:
		return "Malta"
	case 134:
		return "MarshallIslands"
	case 135:
		return "Martinique"
	case 136:
		return "Mauritania"
	case 137:
		return "Mauritius"
	case 138:
		return "Mayotte"
	case 139:
		return "Mexico"
	case 140:
		return "Micronesia"
	case 141:
		return "Moldova"
	case 142:
		return "Monaco"
	case 143:
		return "Mongolia"
	case 144:
		return "Montserrat"
	case 145:
		return "Morocco"
	case 146:
		return "Mozambique"
	case 147:
		return "Myanmar"
	case 148:
		return "Namibia"
	case 149:
		return "NauruCountry"
	case 150:
		return "Nepal"
	case 151:
		return "Netherlands"
	case 152:
		return "CuraSao"
	case 153:
		return "NewCaledonia"
	case 154:
		return "NewZealand"
	case 155:
		return "Nicaragua"
	case 156:
		return "Niger"
	case 157:
		return "Nigeria"
	case 158:
		return "Niue"
	case 159:
		return "NorfolkIsland"
	case 160:
		return "NorthernMarianaIslands"
	case 161:
		return "Norway"
	case 162:
		return "Oman"
	case 163:
		return "Pakistan"
	case 164:
		return "Palau"
	case 165:
		return "PalestinianTerritories"
	case 166:
		return "Panama"
	case 167:
		return "PapuaNewGuinea"
	case 168:
		return "Paraguay"
	case 169:
		return "Peru"
	case 170:
		return "Philippines"
	case 171:
		return "Pitcairn"
	case 172:
		return "Poland"
	case 173:
		return "Portugal"
	case 174:
		return "PuertoRico"
	case 175:
		return "Qatar"
	case 176:
		return "Reunion"
	case 177:
		return "Romania"
	case 178:
		return "Russia" // RussianFederation
	case 179:
		return "Rwanda"
	case 180:
		return "SaintKittsAndNevis"
	case 181:
		return "SaintLucia"
	case 182:
		return "SaintVincentAndTheGrenadines"
	case 183:
		return "Samoa"
	case 184:
		return "SanMarino"
	case 185:
		return "SaoTomeAndPrincipe"
	case 186:
		return "SaudiArabia"
	case 187:
		return "Senegal"
	case 188:
		return "Seychelles"
	case 189:
		return "SierraLeone"
	case 190:
		return "Singapore"
	case 191:
		return "Slovakia"
	case 192:
		return "Slovenia"
	case 193:
		return "SolomonIslands"
	case 194:
		return "Somalia"
	case 195:
		return "SouthAfrica"
	case 196:
		return "SouthGeorgiaAndTheSouthSandwichIslands"
	case 197:
		return "Spain"
	case 198:
		return "SriLanka"
	case 199:
		return "SaintHelena"
	case 200:
		return "SaintPierreAndMiquelon"
	case 201:
		return "Sudan"
	case 202:
		return "Suriname"
	case 203:
		return "SvalbardAndJanMayenIslands"
	case 204:
		return "Swaziland"
	case 205:
		return "Sweden"
	case 206:
		return "Switzerland"
	case 207:
		return "Syria" // SyrianArabRepublic
	case 208:
		return "Taiwan"
	case 209:
		return "Tajikistan"
	case 210:
		return "Tanzania"
	case 211:
		return "Thailand"
	case 212:
		return "Togo"
	case 213:
		return "TokelauCountry" // Tokelau
	case 214:
		return "Tonga"
	case 215:
		return "TrinidadAndTobago"
	case 216:
		return "Tunisia"
	case 217:
		return "Turkey"
	case 218:
		return "Turkmenistan"
	case 219:
		return "TurksAndCaicosIslands"
	case 220:
		return "TuvaluCountry" // Tuvalu
	case 221:
		return "Uganda"
	case 222:
		return "Ukraine"
	case 223:
		return "UnitedArabEmirates"
	case 224:
		return "UnitedKingdom"
	case 225:
		return "UnitedStates"
	case 226:
		return "UnitedStatesMinorOutlyingIslands"
	case 227:
		return "Uruguay"
	case 228:
		return "Uzbekistan"
	case 229:
		return "Vanuatu"
	case 230:
		return "VaticanCityState"
	case 231:
		return "Venezuela"
	case 232:
		return "Vietnam"
	case 233:
		return "BritishVirginIslands"
	case 234:
		return "UnitedStatesVirginIslands"
	case 235:
		return "WallisAndFutunaIslands"
	case 236:
		return "WesternSahara"
	case 237:
		return "Yemen"
	case 238:
		return "CanaryIslands"
	case 239:
		return "Zambia"
	case 240:
		return "Zimbabwe"
	case 241:
		return "ClippertonIsland"
	case 242:
		return "Montenegro"
	case 243:
		return "Serbia"
	case 244:
		return "SaintBarthelemy"
	case 245:
		return "SaintMartin"
	case 246:
		return "LatinAmerica" // LatinAmericaAndTheCaribbean
	case 247:
		return "AscensionIsland"
	case 248:
		return "AlandIslands"
	case 249:
		return "DiegoGarcia"
	case 250:
		return "CeutaAndMelilla"
	case 251:
		return "IsleOfMan"
	case 252:
		return "Jersey"
	case 253:
		return "TristanDaCunha"
	case 254:
		return "SouthSudan"
	case 255:
		return "Bonaire"
	case 256:
		return "SintMaarten"
	case 257:
		return "Kosovo"
	case 258:
		return "EuropeanUnion"
	case 259:
		return "OutlyingOceania"
	case 260:
		return "World"
	case 261:
		return "Europe" // LastCountry
	}
	panic("no such country")
}
