// Code generated by locale_generate.go from Qt 5.13. DO NOT EDIT.
package qrc

import "testing"

func TestLanguage(t *testing.T) {
	if LanguageAnyLanguage != 0 || LanguageAnyLanguage.String() != "AnyLanguage" {
		t.Errorf("%q incorrect", "AnyLanguage")
	}
	if LanguageC != 1 || LanguageC.String() != "C" {
		t.Errorf("%q incorrect", "C")
	}
	if LanguageAbkhazian != 2 || LanguageAbkhazian.String() != "Abkhazian" {
		t.Errorf("%q incorrect", "Abkhazian")
	}
	if LanguageAfan != 3 || LanguageAfan.String() != "Oromo" {
		t.Errorf("%q incorrect", "Afan")
	}
	if LanguageOromo != 3 || LanguageOromo.String() != "Oromo" {
		t.Errorf("%q incorrect", "Oromo")
	}
	if LanguageAfar != 4 || LanguageAfar.String() != "Afar" {
		t.Errorf("%q incorrect", "Afar")
	}
	if LanguageAfrikaans != 5 || LanguageAfrikaans.String() != "Afrikaans" {
		t.Errorf("%q incorrect", "Afrikaans")
	}
	if LanguageAlbanian != 6 || LanguageAlbanian.String() != "Albanian" {
		t.Errorf("%q incorrect", "Albanian")
	}
	if LanguageAmharic != 7 || LanguageAmharic.String() != "Amharic" {
		t.Errorf("%q incorrect", "Amharic")
	}
	if LanguageArabic != 8 || LanguageArabic.String() != "Arabic" {
		t.Errorf("%q incorrect", "Arabic")
	}
	if LanguageArmenian != 9 || LanguageArmenian.String() != "Armenian" {
		t.Errorf("%q incorrect", "Armenian")
	}
	if LanguageAssamese != 10 || LanguageAssamese.String() != "Assamese" {
		t.Errorf("%q incorrect", "Assamese")
	}
	if LanguageAymara != 11 || LanguageAymara.String() != "Aymara" {
		t.Errorf("%q incorrect", "Aymara")
	}
	if LanguageAzerbaijani != 12 || LanguageAzerbaijani.String() != "Azerbaijani" {
		t.Errorf("%q incorrect", "Azerbaijani")
	}
	if LanguageBashkir != 13 || LanguageBashkir.String() != "Bashkir" {
		t.Errorf("%q incorrect", "Bashkir")
	}
	if LanguageBasque != 14 || LanguageBasque.String() != "Basque" {
		t.Errorf("%q incorrect", "Basque")
	}
	if LanguageBengali != 15 || LanguageBengali.String() != "Bengali" {
		t.Errorf("%q incorrect", "Bengali")
	}
	if LanguageBhutani != 16 || LanguageBhutani.String() != "Dzongkha" {
		t.Errorf("%q incorrect", "Bhutani")
	}
	if LanguageDzongkha != 16 || LanguageDzongkha.String() != "Dzongkha" {
		t.Errorf("%q incorrect", "Dzongkha")
	}
	if LanguageBihari != 17 || LanguageBihari.String() != "Bihari" {
		t.Errorf("%q incorrect", "Bihari")
	}
	if LanguageBislama != 18 || LanguageBislama.String() != "Bislama" {
		t.Errorf("%q incorrect", "Bislama")
	}
	if LanguageBreton != 19 || LanguageBreton.String() != "Breton" {
		t.Errorf("%q incorrect", "Breton")
	}
	if LanguageBulgarian != 20 || LanguageBulgarian.String() != "Bulgarian" {
		t.Errorf("%q incorrect", "Bulgarian")
	}
	if LanguageBurmese != 21 || LanguageBurmese.String() != "Burmese" {
		t.Errorf("%q incorrect", "Burmese")
	}
	if LanguageByelorussian != 22 || LanguageByelorussian.String() != "Belarusian" {
		t.Errorf("%q incorrect", "Byelorussian")
	}
	if LanguageBelarusian != 22 || LanguageBelarusian.String() != "Belarusian" {
		t.Errorf("%q incorrect", "Belarusian")
	}
	if LanguageKhmer != 23 || LanguageKhmer.String() != "Khmer" {
		t.Errorf("%q incorrect", "Khmer")
	}
	if LanguageCambodian != 23 || LanguageCambodian.String() != "Khmer" {
		t.Errorf("%q incorrect", "Cambodian")
	}
	if LanguageCatalan != 24 || LanguageCatalan.String() != "Catalan" {
		t.Errorf("%q incorrect", "Catalan")
	}
	if LanguageChinese != 25 || LanguageChinese.String() != "Chinese" {
		t.Errorf("%q incorrect", "Chinese")
	}
	if LanguageCorsican != 26 || LanguageCorsican.String() != "Corsican" {
		t.Errorf("%q incorrect", "Corsican")
	}
	if LanguageCroatian != 27 || LanguageCroatian.String() != "Croatian" {
		t.Errorf("%q incorrect", "Croatian")
	}
	if LanguageCzech != 28 || LanguageCzech.String() != "Czech" {
		t.Errorf("%q incorrect", "Czech")
	}
	if LanguageDanish != 29 || LanguageDanish.String() != "Danish" {
		t.Errorf("%q incorrect", "Danish")
	}
	if LanguageDutch != 30 || LanguageDutch.String() != "Dutch" {
		t.Errorf("%q incorrect", "Dutch")
	}
	if LanguageEnglish != 31 || LanguageEnglish.String() != "English" {
		t.Errorf("%q incorrect", "English")
	}
	if LanguageEsperanto != 32 || LanguageEsperanto.String() != "Esperanto" {
		t.Errorf("%q incorrect", "Esperanto")
	}
	if LanguageEstonian != 33 || LanguageEstonian.String() != "Estonian" {
		t.Errorf("%q incorrect", "Estonian")
	}
	if LanguageFaroese != 34 || LanguageFaroese.String() != "Faroese" {
		t.Errorf("%q incorrect", "Faroese")
	}
	if LanguageFijian != 35 || LanguageFijian.String() != "Fijian" {
		t.Errorf("%q incorrect", "Fijian")
	}
	if LanguageFinnish != 36 || LanguageFinnish.String() != "Finnish" {
		t.Errorf("%q incorrect", "Finnish")
	}
	if LanguageFrench != 37 || LanguageFrench.String() != "French" {
		t.Errorf("%q incorrect", "French")
	}
	if LanguageWesternFrisian != 38 || LanguageWesternFrisian.String() != "WesternFrisian" {
		t.Errorf("%q incorrect", "WesternFrisian")
	}
	if LanguageFrisian != 38 || LanguageFrisian.String() != "WesternFrisian" {
		t.Errorf("%q incorrect", "Frisian")
	}
	if LanguageGaelic != 39 || LanguageGaelic.String() != "Gaelic" {
		t.Errorf("%q incorrect", "Gaelic")
	}
	if LanguageGalician != 40 || LanguageGalician.String() != "Galician" {
		t.Errorf("%q incorrect", "Galician")
	}
	if LanguageGeorgian != 41 || LanguageGeorgian.String() != "Georgian" {
		t.Errorf("%q incorrect", "Georgian")
	}
	if LanguageGerman != 42 || LanguageGerman.String() != "German" {
		t.Errorf("%q incorrect", "German")
	}
	if LanguageGreek != 43 || LanguageGreek.String() != "Greek" {
		t.Errorf("%q incorrect", "Greek")
	}
	if LanguageGreenlandic != 44 || LanguageGreenlandic.String() != "Greenlandic" {
		t.Errorf("%q incorrect", "Greenlandic")
	}
	if LanguageGuarani != 45 || LanguageGuarani.String() != "Guarani" {
		t.Errorf("%q incorrect", "Guarani")
	}
	if LanguageGujarati != 46 || LanguageGujarati.String() != "Gujarati" {
		t.Errorf("%q incorrect", "Gujarati")
	}
	if LanguageHausa != 47 || LanguageHausa.String() != "Hausa" {
		t.Errorf("%q incorrect", "Hausa")
	}
	if LanguageHebrew != 48 || LanguageHebrew.String() != "Hebrew" {
		t.Errorf("%q incorrect", "Hebrew")
	}
	if LanguageHindi != 49 || LanguageHindi.String() != "Hindi" {
		t.Errorf("%q incorrect", "Hindi")
	}
	if LanguageHungarian != 50 || LanguageHungarian.String() != "Hungarian" {
		t.Errorf("%q incorrect", "Hungarian")
	}
	if LanguageIcelandic != 51 || LanguageIcelandic.String() != "Icelandic" {
		t.Errorf("%q incorrect", "Icelandic")
	}
	if LanguageIndonesian != 52 || LanguageIndonesian.String() != "Indonesian" {
		t.Errorf("%q incorrect", "Indonesian")
	}
	if LanguageInterlingua != 53 || LanguageInterlingua.String() != "Interlingua" {
		t.Errorf("%q incorrect", "Interlingua")
	}
	if LanguageInterlingue != 54 || LanguageInterlingue.String() != "Interlingue" {
		t.Errorf("%q incorrect", "Interlingue")
	}
	if LanguageInuktitut != 55 || LanguageInuktitut.String() != "Inuktitut" {
		t.Errorf("%q incorrect", "Inuktitut")
	}
	if LanguageInupiak != 56 || LanguageInupiak.String() != "Inupiak" {
		t.Errorf("%q incorrect", "Inupiak")
	}
	if LanguageIrish != 57 || LanguageIrish.String() != "Irish" {
		t.Errorf("%q incorrect", "Irish")
	}
	if LanguageItalian != 58 || LanguageItalian.String() != "Italian" {
		t.Errorf("%q incorrect", "Italian")
	}
	if LanguageJapanese != 59 || LanguageJapanese.String() != "Japanese" {
		t.Errorf("%q incorrect", "Japanese")
	}
	if LanguageJavanese != 60 || LanguageJavanese.String() != "Javanese" {
		t.Errorf("%q incorrect", "Javanese")
	}
	if LanguageKannada != 61 || LanguageKannada.String() != "Kannada" {
		t.Errorf("%q incorrect", "Kannada")
	}
	if LanguageKashmiri != 62 || LanguageKashmiri.String() != "Kashmiri" {
		t.Errorf("%q incorrect", "Kashmiri")
	}
	if LanguageKazakh != 63 || LanguageKazakh.String() != "Kazakh" {
		t.Errorf("%q incorrect", "Kazakh")
	}
	if LanguageKinyarwanda != 64 || LanguageKinyarwanda.String() != "Kinyarwanda" {
		t.Errorf("%q incorrect", "Kinyarwanda")
	}
	if LanguageKirghiz != 65 || LanguageKirghiz.String() != "Kirghiz" {
		t.Errorf("%q incorrect", "Kirghiz")
	}
	if LanguageKorean != 66 || LanguageKorean.String() != "Korean" {
		t.Errorf("%q incorrect", "Korean")
	}
	if LanguageKurdish != 67 || LanguageKurdish.String() != "Kurdish" {
		t.Errorf("%q incorrect", "Kurdish")
	}
	if LanguageRundi != 68 || LanguageRundi.String() != "Rundi" {
		t.Errorf("%q incorrect", "Rundi")
	}
	if LanguageKurundi != 68 || LanguageKurundi.String() != "Rundi" {
		t.Errorf("%q incorrect", "Kurundi")
	}
	if LanguageLao != 69 || LanguageLao.String() != "Lao" {
		t.Errorf("%q incorrect", "Lao")
	}
	if LanguageLatin != 70 || LanguageLatin.String() != "Latin" {
		t.Errorf("%q incorrect", "Latin")
	}
	if LanguageLatvian != 71 || LanguageLatvian.String() != "Latvian" {
		t.Errorf("%q incorrect", "Latvian")
	}
	if LanguageLingala != 72 || LanguageLingala.String() != "Lingala" {
		t.Errorf("%q incorrect", "Lingala")
	}
	if LanguageLithuanian != 73 || LanguageLithuanian.String() != "Lithuanian" {
		t.Errorf("%q incorrect", "Lithuanian")
	}
	if LanguageMacedonian != 74 || LanguageMacedonian.String() != "Macedonian" {
		t.Errorf("%q incorrect", "Macedonian")
	}
	if LanguageMalagasy != 75 || LanguageMalagasy.String() != "Malagasy" {
		t.Errorf("%q incorrect", "Malagasy")
	}
	if LanguageMalay != 76 || LanguageMalay.String() != "Malay" {
		t.Errorf("%q incorrect", "Malay")
	}
	if LanguageMalayalam != 77 || LanguageMalayalam.String() != "Malayalam" {
		t.Errorf("%q incorrect", "Malayalam")
	}
	if LanguageMaltese != 78 || LanguageMaltese.String() != "Maltese" {
		t.Errorf("%q incorrect", "Maltese")
	}
	if LanguageMaori != 79 || LanguageMaori.String() != "Maori" {
		t.Errorf("%q incorrect", "Maori")
	}
	if LanguageMarathi != 80 || LanguageMarathi.String() != "Marathi" {
		t.Errorf("%q incorrect", "Marathi")
	}
	if LanguageMarshallese != 81 || LanguageMarshallese.String() != "Marshallese" {
		t.Errorf("%q incorrect", "Marshallese")
	}
	if LanguageMongolian != 82 || LanguageMongolian.String() != "Mongolian" {
		t.Errorf("%q incorrect", "Mongolian")
	}
	if LanguageNauruLanguage != 83 || LanguageNauruLanguage.String() != "NauruLanguage" {
		t.Errorf("%q incorrect", "NauruLanguage")
	}
	if LanguageNepali != 84 || LanguageNepali.String() != "Nepali" {
		t.Errorf("%q incorrect", "Nepali")
	}
	if LanguageNorwegianBokmal != 85 || LanguageNorwegianBokmal.String() != "NorwegianBokmal" {
		t.Errorf("%q incorrect", "NorwegianBokmal")
	}
	if LanguageNorwegian != 85 || LanguageNorwegian.String() != "NorwegianBokmal" {
		t.Errorf("%q incorrect", "Norwegian")
	}
	if LanguageOccitan != 86 || LanguageOccitan.String() != "Occitan" {
		t.Errorf("%q incorrect", "Occitan")
	}
	if LanguageOriya != 87 || LanguageOriya.String() != "Oriya" {
		t.Errorf("%q incorrect", "Oriya")
	}
	if LanguagePashto != 88 || LanguagePashto.String() != "Pashto" {
		t.Errorf("%q incorrect", "Pashto")
	}
	if LanguagePersian != 89 || LanguagePersian.String() != "Persian" {
		t.Errorf("%q incorrect", "Persian")
	}
	if LanguagePolish != 90 || LanguagePolish.String() != "Polish" {
		t.Errorf("%q incorrect", "Polish")
	}
	if LanguagePortuguese != 91 || LanguagePortuguese.String() != "Portuguese" {
		t.Errorf("%q incorrect", "Portuguese")
	}
	if LanguagePunjabi != 92 || LanguagePunjabi.String() != "Punjabi" {
		t.Errorf("%q incorrect", "Punjabi")
	}
	if LanguageQuechua != 93 || LanguageQuechua.String() != "Quechua" {
		t.Errorf("%q incorrect", "Quechua")
	}
	if LanguageRomansh != 94 || LanguageRomansh.String() != "Romansh" {
		t.Errorf("%q incorrect", "Romansh")
	}
	if LanguageRhaetoRomance != 94 || LanguageRhaetoRomance.String() != "Romansh" {
		t.Errorf("%q incorrect", "RhaetoRomance")
	}
	if LanguageMoldavian != 95 || LanguageMoldavian.String() != "Romanian" {
		t.Errorf("%q incorrect", "Moldavian")
	}
	if LanguageRomanian != 95 || LanguageRomanian.String() != "Romanian" {
		t.Errorf("%q incorrect", "Romanian")
	}
	if LanguageRussian != 96 || LanguageRussian.String() != "Russian" {
		t.Errorf("%q incorrect", "Russian")
	}
	if LanguageSamoan != 97 || LanguageSamoan.String() != "Samoan" {
		t.Errorf("%q incorrect", "Samoan")
	}
	if LanguageSango != 98 || LanguageSango.String() != "Sango" {
		t.Errorf("%q incorrect", "Sango")
	}
	if LanguageSanskrit != 99 || LanguageSanskrit.String() != "Sanskrit" {
		t.Errorf("%q incorrect", "Sanskrit")
	}
	if LanguageSerboCroatian != 100 || LanguageSerboCroatian.String() != "Serbian" {
		t.Errorf("%q incorrect", "SerboCroatian")
	}
	if LanguageSerbian != 100 || LanguageSerbian.String() != "Serbian" {
		t.Errorf("%q incorrect", "Serbian")
	}
	if LanguageOssetic != 101 || LanguageOssetic.String() != "Ossetic" {
		t.Errorf("%q incorrect", "Ossetic")
	}
	if LanguageSouthernSotho != 102 || LanguageSouthernSotho.String() != "SouthernSotho" {
		t.Errorf("%q incorrect", "SouthernSotho")
	}
	if LanguageTswana != 103 || LanguageTswana.String() != "Tswana" {
		t.Errorf("%q incorrect", "Tswana")
	}
	if LanguageShona != 104 || LanguageShona.String() != "Shona" {
		t.Errorf("%q incorrect", "Shona")
	}
	if LanguageSindhi != 105 || LanguageSindhi.String() != "Sindhi" {
		t.Errorf("%q incorrect", "Sindhi")
	}
	if LanguageSinhala != 106 || LanguageSinhala.String() != "Sinhala" {
		t.Errorf("%q incorrect", "Sinhala")
	}
	if LanguageSwati != 107 || LanguageSwati.String() != "Swati" {
		t.Errorf("%q incorrect", "Swati")
	}
	if LanguageSlovak != 108 || LanguageSlovak.String() != "Slovak" {
		t.Errorf("%q incorrect", "Slovak")
	}
	if LanguageSlovenian != 109 || LanguageSlovenian.String() != "Slovenian" {
		t.Errorf("%q incorrect", "Slovenian")
	}
	if LanguageSomali != 110 || LanguageSomali.String() != "Somali" {
		t.Errorf("%q incorrect", "Somali")
	}
	if LanguageSpanish != 111 || LanguageSpanish.String() != "Spanish" {
		t.Errorf("%q incorrect", "Spanish")
	}
	if LanguageSundanese != 112 || LanguageSundanese.String() != "Sundanese" {
		t.Errorf("%q incorrect", "Sundanese")
	}
	if LanguageSwahili != 113 || LanguageSwahili.String() != "Swahili" {
		t.Errorf("%q incorrect", "Swahili")
	}
	if LanguageSwedish != 114 || LanguageSwedish.String() != "Swedish" {
		t.Errorf("%q incorrect", "Swedish")
	}
	if LanguageSardinian != 115 || LanguageSardinian.String() != "Sardinian" {
		t.Errorf("%q incorrect", "Sardinian")
	}
	if LanguageTajik != 116 || LanguageTajik.String() != "Tajik" {
		t.Errorf("%q incorrect", "Tajik")
	}
	if LanguageTamil != 117 || LanguageTamil.String() != "Tamil" {
		t.Errorf("%q incorrect", "Tamil")
	}
	if LanguageTatar != 118 || LanguageTatar.String() != "Tatar" {
		t.Errorf("%q incorrect", "Tatar")
	}
	if LanguageTelugu != 119 || LanguageTelugu.String() != "Telugu" {
		t.Errorf("%q incorrect", "Telugu")
	}
	if LanguageThai != 120 || LanguageThai.String() != "Thai" {
		t.Errorf("%q incorrect", "Thai")
	}
	if LanguageTibetan != 121 || LanguageTibetan.String() != "Tibetan" {
		t.Errorf("%q incorrect", "Tibetan")
	}
	if LanguageTigrinya != 122 || LanguageTigrinya.String() != "Tigrinya" {
		t.Errorf("%q incorrect", "Tigrinya")
	}
	if LanguageTongan != 123 || LanguageTongan.String() != "Tongan" {
		t.Errorf("%q incorrect", "Tongan")
	}
	if LanguageTsonga != 124 || LanguageTsonga.String() != "Tsonga" {
		t.Errorf("%q incorrect", "Tsonga")
	}
	if LanguageTurkish != 125 || LanguageTurkish.String() != "Turkish" {
		t.Errorf("%q incorrect", "Turkish")
	}
	if LanguageTurkmen != 126 || LanguageTurkmen.String() != "Turkmen" {
		t.Errorf("%q incorrect", "Turkmen")
	}
	if LanguageTahitian != 127 || LanguageTahitian.String() != "Tahitian" {
		t.Errorf("%q incorrect", "Tahitian")
	}
	if LanguageUigur != 128 || LanguageUigur.String() != "Uighur" {
		t.Errorf("%q incorrect", "Uigur")
	}
	if LanguageUighur != 128 || LanguageUighur.String() != "Uighur" {
		t.Errorf("%q incorrect", "Uighur")
	}
	if LanguageUkrainian != 129 || LanguageUkrainian.String() != "Ukrainian" {
		t.Errorf("%q incorrect", "Ukrainian")
	}
	if LanguageUrdu != 130 || LanguageUrdu.String() != "Urdu" {
		t.Errorf("%q incorrect", "Urdu")
	}
	if LanguageUzbek != 131 || LanguageUzbek.String() != "Uzbek" {
		t.Errorf("%q incorrect", "Uzbek")
	}
	if LanguageVietnamese != 132 || LanguageVietnamese.String() != "Vietnamese" {
		t.Errorf("%q incorrect", "Vietnamese")
	}
	if LanguageVolapuk != 133 || LanguageVolapuk.String() != "Volapuk" {
		t.Errorf("%q incorrect", "Volapuk")
	}
	if LanguageWelsh != 134 || LanguageWelsh.String() != "Welsh" {
		t.Errorf("%q incorrect", "Welsh")
	}
	if LanguageWolof != 135 || LanguageWolof.String() != "Wolof" {
		t.Errorf("%q incorrect", "Wolof")
	}
	if LanguageXhosa != 136 || LanguageXhosa.String() != "Xhosa" {
		t.Errorf("%q incorrect", "Xhosa")
	}
	if LanguageYiddish != 137 || LanguageYiddish.String() != "Yiddish" {
		t.Errorf("%q incorrect", "Yiddish")
	}
	if LanguageYoruba != 138 || LanguageYoruba.String() != "Yoruba" {
		t.Errorf("%q incorrect", "Yoruba")
	}
	if LanguageZhuang != 139 || LanguageZhuang.String() != "Zhuang" {
		t.Errorf("%q incorrect", "Zhuang")
	}
	if LanguageZulu != 140 || LanguageZulu.String() != "Zulu" {
		t.Errorf("%q incorrect", "Zulu")
	}
	if LanguageNorwegianNynorsk != 141 || LanguageNorwegianNynorsk.String() != "NorwegianNynorsk" {
		t.Errorf("%q incorrect", "NorwegianNynorsk")
	}
	if LanguageBosnian != 142 || LanguageBosnian.String() != "Bosnian" {
		t.Errorf("%q incorrect", "Bosnian")
	}
	if LanguageDivehi != 143 || LanguageDivehi.String() != "Divehi" {
		t.Errorf("%q incorrect", "Divehi")
	}
	if LanguageManx != 144 || LanguageManx.String() != "Manx" {
		t.Errorf("%q incorrect", "Manx")
	}
	if LanguageCornish != 145 || LanguageCornish.String() != "Cornish" {
		t.Errorf("%q incorrect", "Cornish")
	}
	if LanguageTwi != 146 || LanguageTwi.String() != "Akan" {
		t.Errorf("%q incorrect", "Twi")
	}
	if LanguageAkan != 146 || LanguageAkan.String() != "Akan" {
		t.Errorf("%q incorrect", "Akan")
	}
	if LanguageKonkani != 147 || LanguageKonkani.String() != "Konkani" {
		t.Errorf("%q incorrect", "Konkani")
	}
	if LanguageGa != 148 || LanguageGa.String() != "Ga" {
		t.Errorf("%q incorrect", "Ga")
	}
	if LanguageIgbo != 149 || LanguageIgbo.String() != "Igbo" {
		t.Errorf("%q incorrect", "Igbo")
	}
	if LanguageKamba != 150 || LanguageKamba.String() != "Kamba" {
		t.Errorf("%q incorrect", "Kamba")
	}
	if LanguageSyriac != 151 || LanguageSyriac.String() != "Syriac" {
		t.Errorf("%q incorrect", "Syriac")
	}
	if LanguageBlin != 152 || LanguageBlin.String() != "Blin" {
		t.Errorf("%q incorrect", "Blin")
	}
	if LanguageGeez != 153 || LanguageGeez.String() != "Geez" {
		t.Errorf("%q incorrect", "Geez")
	}
	if LanguageKoro != 154 || LanguageKoro.String() != "Koro" {
		t.Errorf("%q incorrect", "Koro")
	}
	if LanguageSidamo != 155 || LanguageSidamo.String() != "Sidamo" {
		t.Errorf("%q incorrect", "Sidamo")
	}
	if LanguageAtsam != 156 || LanguageAtsam.String() != "Atsam" {
		t.Errorf("%q incorrect", "Atsam")
	}
	if LanguageTigre != 157 || LanguageTigre.String() != "Tigre" {
		t.Errorf("%q incorrect", "Tigre")
	}
	if LanguageJju != 158 || LanguageJju.String() != "Jju" {
		t.Errorf("%q incorrect", "Jju")
	}
	if LanguageFriulian != 159 || LanguageFriulian.String() != "Friulian" {
		t.Errorf("%q incorrect", "Friulian")
	}
	if LanguageVenda != 160 || LanguageVenda.String() != "Venda" {
		t.Errorf("%q incorrect", "Venda")
	}
	if LanguageEwe != 161 || LanguageEwe.String() != "Ewe" {
		t.Errorf("%q incorrect", "Ewe")
	}
	if LanguageWalamo != 162 || LanguageWalamo.String() != "Walamo" {
		t.Errorf("%q incorrect", "Walamo")
	}
	if LanguageHawaiian != 163 || LanguageHawaiian.String() != "Hawaiian" {
		t.Errorf("%q incorrect", "Hawaiian")
	}
	if LanguageTyap != 164 || LanguageTyap.String() != "Tyap" {
		t.Errorf("%q incorrect", "Tyap")
	}
	if LanguageNyanja != 165 || LanguageNyanja.String() != "Nyanja" {
		t.Errorf("%q incorrect", "Nyanja")
	}
	if LanguageChewa != 165 || LanguageChewa.String() != "Nyanja" {
		t.Errorf("%q incorrect", "Chewa")
	}
	if LanguageFilipino != 166 || LanguageFilipino.String() != "Filipino" {
		t.Errorf("%q incorrect", "Filipino")
	}
	if LanguageTagalog != 166 || LanguageTagalog.String() != "Filipino" {
		t.Errorf("%q incorrect", "Tagalog")
	}
	if LanguageSwissGerman != 167 || LanguageSwissGerman.String() != "SwissGerman" {
		t.Errorf("%q incorrect", "SwissGerman")
	}
	if LanguageSichuanYi != 168 || LanguageSichuanYi.String() != "SichuanYi" {
		t.Errorf("%q incorrect", "SichuanYi")
	}
	if LanguageKpelle != 169 || LanguageKpelle.String() != "Kpelle" {
		t.Errorf("%q incorrect", "Kpelle")
	}
	if LanguageLowGerman != 170 || LanguageLowGerman.String() != "LowGerman" {
		t.Errorf("%q incorrect", "LowGerman")
	}
	if LanguageSouthNdebele != 171 || LanguageSouthNdebele.String() != "SouthNdebele" {
		t.Errorf("%q incorrect", "SouthNdebele")
	}
	if LanguageNorthernSotho != 172 || LanguageNorthernSotho.String() != "NorthernSotho" {
		t.Errorf("%q incorrect", "NorthernSotho")
	}
	if LanguageNorthernSami != 173 || LanguageNorthernSami.String() != "NorthernSami" {
		t.Errorf("%q incorrect", "NorthernSami")
	}
	if LanguageTaroko != 174 || LanguageTaroko.String() != "Taroko" {
		t.Errorf("%q incorrect", "Taroko")
	}
	if LanguageGusii != 175 || LanguageGusii.String() != "Gusii" {
		t.Errorf("%q incorrect", "Gusii")
	}
	if LanguageTaita != 176 || LanguageTaita.String() != "Taita" {
		t.Errorf("%q incorrect", "Taita")
	}
	if LanguageFulah != 177 || LanguageFulah.String() != "Fulah" {
		t.Errorf("%q incorrect", "Fulah")
	}
	if LanguageKikuyu != 178 || LanguageKikuyu.String() != "Kikuyu" {
		t.Errorf("%q incorrect", "Kikuyu")
	}
	if LanguageSamburu != 179 || LanguageSamburu.String() != "Samburu" {
		t.Errorf("%q incorrect", "Samburu")
	}
	if LanguageSena != 180 || LanguageSena.String() != "Sena" {
		t.Errorf("%q incorrect", "Sena")
	}
	if LanguageNorthNdebele != 181 || LanguageNorthNdebele.String() != "NorthNdebele" {
		t.Errorf("%q incorrect", "NorthNdebele")
	}
	if LanguageRombo != 182 || LanguageRombo.String() != "Rombo" {
		t.Errorf("%q incorrect", "Rombo")
	}
	if LanguageTachelhit != 183 || LanguageTachelhit.String() != "Tachelhit" {
		t.Errorf("%q incorrect", "Tachelhit")
	}
	if LanguageKabyle != 184 || LanguageKabyle.String() != "Kabyle" {
		t.Errorf("%q incorrect", "Kabyle")
	}
	if LanguageNyankole != 185 || LanguageNyankole.String() != "Nyankole" {
		t.Errorf("%q incorrect", "Nyankole")
	}
	if LanguageBena != 186 || LanguageBena.String() != "Bena" {
		t.Errorf("%q incorrect", "Bena")
	}
	if LanguageVunjo != 187 || LanguageVunjo.String() != "Vunjo" {
		t.Errorf("%q incorrect", "Vunjo")
	}
	if LanguageBambara != 188 || LanguageBambara.String() != "Bambara" {
		t.Errorf("%q incorrect", "Bambara")
	}
	if LanguageEmbu != 189 || LanguageEmbu.String() != "Embu" {
		t.Errorf("%q incorrect", "Embu")
	}
	if LanguageCherokee != 190 || LanguageCherokee.String() != "Cherokee" {
		t.Errorf("%q incorrect", "Cherokee")
	}
	if LanguageMorisyen != 191 || LanguageMorisyen.String() != "Morisyen" {
		t.Errorf("%q incorrect", "Morisyen")
	}
	if LanguageMakonde != 192 || LanguageMakonde.String() != "Makonde" {
		t.Errorf("%q incorrect", "Makonde")
	}
	if LanguageLangi != 193 || LanguageLangi.String() != "Langi" {
		t.Errorf("%q incorrect", "Langi")
	}
	if LanguageGanda != 194 || LanguageGanda.String() != "Ganda" {
		t.Errorf("%q incorrect", "Ganda")
	}
	if LanguageBemba != 195 || LanguageBemba.String() != "Bemba" {
		t.Errorf("%q incorrect", "Bemba")
	}
	if LanguageKabuverdianu != 196 || LanguageKabuverdianu.String() != "Kabuverdianu" {
		t.Errorf("%q incorrect", "Kabuverdianu")
	}
	if LanguageMeru != 197 || LanguageMeru.String() != "Meru" {
		t.Errorf("%q incorrect", "Meru")
	}
	if LanguageKalenjin != 198 || LanguageKalenjin.String() != "Kalenjin" {
		t.Errorf("%q incorrect", "Kalenjin")
	}
	if LanguageNama != 199 || LanguageNama.String() != "Nama" {
		t.Errorf("%q incorrect", "Nama")
	}
	if LanguageMachame != 200 || LanguageMachame.String() != "Machame" {
		t.Errorf("%q incorrect", "Machame")
	}
	if LanguageColognian != 201 || LanguageColognian.String() != "Colognian" {
		t.Errorf("%q incorrect", "Colognian")
	}
	if LanguageMasai != 202 || LanguageMasai.String() != "Masai" {
		t.Errorf("%q incorrect", "Masai")
	}
	if LanguageSoga != 203 || LanguageSoga.String() != "Soga" {
		t.Errorf("%q incorrect", "Soga")
	}
	if LanguageLuyia != 204 || LanguageLuyia.String() != "Luyia" {
		t.Errorf("%q incorrect", "Luyia")
	}
	if LanguageAsu != 205 || LanguageAsu.String() != "Asu" {
		t.Errorf("%q incorrect", "Asu")
	}
	if LanguageTeso != 206 || LanguageTeso.String() != "Teso" {
		t.Errorf("%q incorrect", "Teso")
	}
	if LanguageSaho != 207 || LanguageSaho.String() != "Saho" {
		t.Errorf("%q incorrect", "Saho")
	}
	if LanguageKoyraChiini != 208 || LanguageKoyraChiini.String() != "KoyraChiini" {
		t.Errorf("%q incorrect", "KoyraChiini")
	}
	if LanguageRwa != 209 || LanguageRwa.String() != "Rwa" {
		t.Errorf("%q incorrect", "Rwa")
	}
	if LanguageLuo != 210 || LanguageLuo.String() != "Luo" {
		t.Errorf("%q incorrect", "Luo")
	}
	if LanguageChiga != 211 || LanguageChiga.String() != "Chiga" {
		t.Errorf("%q incorrect", "Chiga")
	}
	if LanguageCentralMoroccoTamazight != 212 || LanguageCentralMoroccoTamazight.String() != "CentralMoroccoTamazight" {
		t.Errorf("%q incorrect", "CentralMoroccoTamazight")
	}
	if LanguageKoyraboroSenni != 213 || LanguageKoyraboroSenni.String() != "KoyraboroSenni" {
		t.Errorf("%q incorrect", "KoyraboroSenni")
	}
	if LanguageShambala != 214 || LanguageShambala.String() != "Shambala" {
		t.Errorf("%q incorrect", "Shambala")
	}
	if LanguageBodo != 215 || LanguageBodo.String() != "Bodo" {
		t.Errorf("%q incorrect", "Bodo")
	}
	if LanguageAvaric != 216 || LanguageAvaric.String() != "Avaric" {
		t.Errorf("%q incorrect", "Avaric")
	}
	if LanguageChamorro != 217 || LanguageChamorro.String() != "Chamorro" {
		t.Errorf("%q incorrect", "Chamorro")
	}
	if LanguageChechen != 218 || LanguageChechen.String() != "Chechen" {
		t.Errorf("%q incorrect", "Chechen")
	}
	if LanguageChurch != 219 || LanguageChurch.String() != "Church" {
		t.Errorf("%q incorrect", "Church")
	}
	if LanguageChuvash != 220 || LanguageChuvash.String() != "Chuvash" {
		t.Errorf("%q incorrect", "Chuvash")
	}
	if LanguageCree != 221 || LanguageCree.String() != "Cree" {
		t.Errorf("%q incorrect", "Cree")
	}
	if LanguageHaitian != 222 || LanguageHaitian.String() != "Haitian" {
		t.Errorf("%q incorrect", "Haitian")
	}
	if LanguageHerero != 223 || LanguageHerero.String() != "Herero" {
		t.Errorf("%q incorrect", "Herero")
	}
	if LanguageHiriMotu != 224 || LanguageHiriMotu.String() != "HiriMotu" {
		t.Errorf("%q incorrect", "HiriMotu")
	}
	if LanguageKanuri != 225 || LanguageKanuri.String() != "Kanuri" {
		t.Errorf("%q incorrect", "Kanuri")
	}
	if LanguageKomi != 226 || LanguageKomi.String() != "Komi" {
		t.Errorf("%q incorrect", "Komi")
	}
	if LanguageKongo != 227 || LanguageKongo.String() != "Kongo" {
		t.Errorf("%q incorrect", "Kongo")
	}
	if LanguageKwanyama != 228 || LanguageKwanyama.String() != "Kwanyama" {
		t.Errorf("%q incorrect", "Kwanyama")
	}
	if LanguageLimburgish != 229 || LanguageLimburgish.String() != "Limburgish" {
		t.Errorf("%q incorrect", "Limburgish")
	}
	if LanguageLubaKatanga != 230 || LanguageLubaKatanga.String() != "LubaKatanga" {
		t.Errorf("%q incorrect", "LubaKatanga")
	}
	if LanguageLuxembourgish != 231 || LanguageLuxembourgish.String() != "Luxembourgish" {
		t.Errorf("%q incorrect", "Luxembourgish")
	}
	if LanguageNavaho != 232 || LanguageNavaho.String() != "Navaho" {
		t.Errorf("%q incorrect", "Navaho")
	}
	if LanguageNdonga != 233 || LanguageNdonga.String() != "Ndonga" {
		t.Errorf("%q incorrect", "Ndonga")
	}
	if LanguageOjibwa != 234 || LanguageOjibwa.String() != "Ojibwa" {
		t.Errorf("%q incorrect", "Ojibwa")
	}
	if LanguagePali != 235 || LanguagePali.String() != "Pali" {
		t.Errorf("%q incorrect", "Pali")
	}
	if LanguageWalloon != 236 || LanguageWalloon.String() != "Walloon" {
		t.Errorf("%q incorrect", "Walloon")
	}
	if LanguageAghem != 237 || LanguageAghem.String() != "Aghem" {
		t.Errorf("%q incorrect", "Aghem")
	}
	if LanguageBasaa != 238 || LanguageBasaa.String() != "Basaa" {
		t.Errorf("%q incorrect", "Basaa")
	}
	if LanguageZarma != 239 || LanguageZarma.String() != "Zarma" {
		t.Errorf("%q incorrect", "Zarma")
	}
	if LanguageDuala != 240 || LanguageDuala.String() != "Duala" {
		t.Errorf("%q incorrect", "Duala")
	}
	if LanguageJolaFonyi != 241 || LanguageJolaFonyi.String() != "JolaFonyi" {
		t.Errorf("%q incorrect", "JolaFonyi")
	}
	if LanguageEwondo != 242 || LanguageEwondo.String() != "Ewondo" {
		t.Errorf("%q incorrect", "Ewondo")
	}
	if LanguageBafia != 243 || LanguageBafia.String() != "Bafia" {
		t.Errorf("%q incorrect", "Bafia")
	}
	if LanguageMakhuwaMeetto != 244 || LanguageMakhuwaMeetto.String() != "MakhuwaMeetto" {
		t.Errorf("%q incorrect", "MakhuwaMeetto")
	}
	if LanguageMundang != 245 || LanguageMundang.String() != "Mundang" {
		t.Errorf("%q incorrect", "Mundang")
	}
	if LanguageKwasio != 246 || LanguageKwasio.String() != "Kwasio" {
		t.Errorf("%q incorrect", "Kwasio")
	}
	if LanguageNuer != 247 || LanguageNuer.String() != "Nuer" {
		t.Errorf("%q incorrect", "Nuer")
	}
	if LanguageSakha != 248 || LanguageSakha.String() != "Sakha" {
		t.Errorf("%q incorrect", "Sakha")
	}
	if LanguageSangu != 249 || LanguageSangu.String() != "Sangu" {
		t.Errorf("%q incorrect", "Sangu")
	}
	if LanguageCongoSwahili != 250 || LanguageCongoSwahili.String() != "CongoSwahili" {
		t.Errorf("%q incorrect", "CongoSwahili")
	}
	if LanguageTasawaq != 251 || LanguageTasawaq.String() != "Tasawaq" {
		t.Errorf("%q incorrect", "Tasawaq")
	}
	if LanguageVai != 252 || LanguageVai.String() != "Vai" {
		t.Errorf("%q incorrect", "Vai")
	}
	if LanguageWalser != 253 || LanguageWalser.String() != "Walser" {
		t.Errorf("%q incorrect", "Walser")
	}
	if LanguageYangben != 254 || LanguageYangben.String() != "Yangben" {
		t.Errorf("%q incorrect", "Yangben")
	}
	if LanguageAvestan != 255 || LanguageAvestan.String() != "Avestan" {
		t.Errorf("%q incorrect", "Avestan")
	}
	if LanguageAsturian != 256 || LanguageAsturian.String() != "Asturian" {
		t.Errorf("%q incorrect", "Asturian")
	}
	if LanguageNgomba != 257 || LanguageNgomba.String() != "Ngomba" {
		t.Errorf("%q incorrect", "Ngomba")
	}
	if LanguageKako != 258 || LanguageKako.String() != "Kako" {
		t.Errorf("%q incorrect", "Kako")
	}
	if LanguageMeta != 259 || LanguageMeta.String() != "Meta" {
		t.Errorf("%q incorrect", "Meta")
	}
	if LanguageNgiemboon != 260 || LanguageNgiemboon.String() != "Ngiemboon" {
		t.Errorf("%q incorrect", "Ngiemboon")
	}
	if LanguageAragonese != 261 || LanguageAragonese.String() != "Aragonese" {
		t.Errorf("%q incorrect", "Aragonese")
	}
	if LanguageAkkadian != 262 || LanguageAkkadian.String() != "Akkadian" {
		t.Errorf("%q incorrect", "Akkadian")
	}
	if LanguageAncientEgyptian != 263 || LanguageAncientEgyptian.String() != "AncientEgyptian" {
		t.Errorf("%q incorrect", "AncientEgyptian")
	}
	if LanguageAncientGreek != 264 || LanguageAncientGreek.String() != "AncientGreek" {
		t.Errorf("%q incorrect", "AncientGreek")
	}
	if LanguageAramaic != 265 || LanguageAramaic.String() != "Aramaic" {
		t.Errorf("%q incorrect", "Aramaic")
	}
	if LanguageBalinese != 266 || LanguageBalinese.String() != "Balinese" {
		t.Errorf("%q incorrect", "Balinese")
	}
	if LanguageBamun != 267 || LanguageBamun.String() != "Bamun" {
		t.Errorf("%q incorrect", "Bamun")
	}
	if LanguageBatakToba != 268 || LanguageBatakToba.String() != "BatakToba" {
		t.Errorf("%q incorrect", "BatakToba")
	}
	if LanguageBuginese != 269 || LanguageBuginese.String() != "Buginese" {
		t.Errorf("%q incorrect", "Buginese")
	}
	if LanguageBuhid != 270 || LanguageBuhid.String() != "Buhid" {
		t.Errorf("%q incorrect", "Buhid")
	}
	if LanguageCarian != 271 || LanguageCarian.String() != "Carian" {
		t.Errorf("%q incorrect", "Carian")
	}
	if LanguageChakma != 272 || LanguageChakma.String() != "Chakma" {
		t.Errorf("%q incorrect", "Chakma")
	}
	if LanguageClassicalMandaic != 273 || LanguageClassicalMandaic.String() != "ClassicalMandaic" {
		t.Errorf("%q incorrect", "ClassicalMandaic")
	}
	if LanguageCoptic != 274 || LanguageCoptic.String() != "Coptic" {
		t.Errorf("%q incorrect", "Coptic")
	}
	if LanguageDogri != 275 || LanguageDogri.String() != "Dogri" {
		t.Errorf("%q incorrect", "Dogri")
	}
	if LanguageEasternCham != 276 || LanguageEasternCham.String() != "EasternCham" {
		t.Errorf("%q incorrect", "EasternCham")
	}
	if LanguageEasternKayah != 277 || LanguageEasternKayah.String() != "EasternKayah" {
		t.Errorf("%q incorrect", "EasternKayah")
	}
	if LanguageEtruscan != 278 || LanguageEtruscan.String() != "Etruscan" {
		t.Errorf("%q incorrect", "Etruscan")
	}
	if LanguageGothic != 279 || LanguageGothic.String() != "Gothic" {
		t.Errorf("%q incorrect", "Gothic")
	}
	if LanguageHanunoo != 280 || LanguageHanunoo.String() != "Hanunoo" {
		t.Errorf("%q incorrect", "Hanunoo")
	}
	if LanguageIngush != 281 || LanguageIngush.String() != "Ingush" {
		t.Errorf("%q incorrect", "Ingush")
	}
	if LanguageLargeFloweryMiao != 282 || LanguageLargeFloweryMiao.String() != "LargeFloweryMiao" {
		t.Errorf("%q incorrect", "LargeFloweryMiao")
	}
	if LanguageLepcha != 283 || LanguageLepcha.String() != "Lepcha" {
		t.Errorf("%q incorrect", "Lepcha")
	}
	if LanguageLimbu != 284 || LanguageLimbu.String() != "Limbu" {
		t.Errorf("%q incorrect", "Limbu")
	}
	if LanguageLisu != 285 || LanguageLisu.String() != "Lisu" {
		t.Errorf("%q incorrect", "Lisu")
	}
	if LanguageLu != 286 || LanguageLu.String() != "Lu" {
		t.Errorf("%q incorrect", "Lu")
	}
	if LanguageLycian != 287 || LanguageLycian.String() != "Lycian" {
		t.Errorf("%q incorrect", "Lycian")
	}
	if LanguageLydian != 288 || LanguageLydian.String() != "Lydian" {
		t.Errorf("%q incorrect", "Lydian")
	}
	if LanguageMandingo != 289 || LanguageMandingo.String() != "Mandingo" {
		t.Errorf("%q incorrect", "Mandingo")
	}
	if LanguageManipuri != 290 || LanguageManipuri.String() != "Manipuri" {
		t.Errorf("%q incorrect", "Manipuri")
	}
	if LanguageMeroitic != 291 || LanguageMeroitic.String() != "Meroitic" {
		t.Errorf("%q incorrect", "Meroitic")
	}
	if LanguageNorthernThai != 292 || LanguageNorthernThai.String() != "NorthernThai" {
		t.Errorf("%q incorrect", "NorthernThai")
	}
	if LanguageOldIrish != 293 || LanguageOldIrish.String() != "OldIrish" {
		t.Errorf("%q incorrect", "OldIrish")
	}
	if LanguageOldNorse != 294 || LanguageOldNorse.String() != "OldNorse" {
		t.Errorf("%q incorrect", "OldNorse")
	}
	if LanguageOldPersian != 295 || LanguageOldPersian.String() != "OldPersian" {
		t.Errorf("%q incorrect", "OldPersian")
	}
	if LanguageOldTurkish != 296 || LanguageOldTurkish.String() != "OldTurkish" {
		t.Errorf("%q incorrect", "OldTurkish")
	}
	if LanguagePahlavi != 297 || LanguagePahlavi.String() != "Pahlavi" {
		t.Errorf("%q incorrect", "Pahlavi")
	}
	if LanguageParthian != 298 || LanguageParthian.String() != "Parthian" {
		t.Errorf("%q incorrect", "Parthian")
	}
	if LanguagePhoenician != 299 || LanguagePhoenician.String() != "Phoenician" {
		t.Errorf("%q incorrect", "Phoenician")
	}
	if LanguagePrakritLanguage != 300 || LanguagePrakritLanguage.String() != "PrakritLanguage" {
		t.Errorf("%q incorrect", "PrakritLanguage")
	}
	if LanguageRejang != 301 || LanguageRejang.String() != "Rejang" {
		t.Errorf("%q incorrect", "Rejang")
	}
	if LanguageSabaean != 302 || LanguageSabaean.String() != "Sabaean" {
		t.Errorf("%q incorrect", "Sabaean")
	}
	if LanguageSamaritan != 303 || LanguageSamaritan.String() != "Samaritan" {
		t.Errorf("%q incorrect", "Samaritan")
	}
	if LanguageSantali != 304 || LanguageSantali.String() != "Santali" {
		t.Errorf("%q incorrect", "Santali")
	}
	if LanguageSaurashtra != 305 || LanguageSaurashtra.String() != "Saurashtra" {
		t.Errorf("%q incorrect", "Saurashtra")
	}
	if LanguageSora != 306 || LanguageSora.String() != "Sora" {
		t.Errorf("%q incorrect", "Sora")
	}
	if LanguageSylheti != 307 || LanguageSylheti.String() != "Sylheti" {
		t.Errorf("%q incorrect", "Sylheti")
	}
	if LanguageTagbanwa != 308 || LanguageTagbanwa.String() != "Tagbanwa" {
		t.Errorf("%q incorrect", "Tagbanwa")
	}
	if LanguageTaiDam != 309 || LanguageTaiDam.String() != "TaiDam" {
		t.Errorf("%q incorrect", "TaiDam")
	}
	if LanguageTaiNua != 310 || LanguageTaiNua.String() != "TaiNua" {
		t.Errorf("%q incorrect", "TaiNua")
	}
	if LanguageUgaritic != 311 || LanguageUgaritic.String() != "Ugaritic" {
		t.Errorf("%q incorrect", "Ugaritic")
	}
	if LanguageAkoose != 312 || LanguageAkoose.String() != "Akoose" {
		t.Errorf("%q incorrect", "Akoose")
	}
	if LanguageLakota != 313 || LanguageLakota.String() != "Lakota" {
		t.Errorf("%q incorrect", "Lakota")
	}
	if LanguageStandardMoroccanTamazight != 314 || LanguageStandardMoroccanTamazight.String() != "StandardMoroccanTamazight" {
		t.Errorf("%q incorrect", "StandardMoroccanTamazight")
	}
	if LanguageMapuche != 315 || LanguageMapuche.String() != "Mapuche" {
		t.Errorf("%q incorrect", "Mapuche")
	}
	if LanguageCentralKurdish != 316 || LanguageCentralKurdish.String() != "CentralKurdish" {
		t.Errorf("%q incorrect", "CentralKurdish")
	}
	if LanguageLowerSorbian != 317 || LanguageLowerSorbian.String() != "LowerSorbian" {
		t.Errorf("%q incorrect", "LowerSorbian")
	}
	if LanguageUpperSorbian != 318 || LanguageUpperSorbian.String() != "UpperSorbian" {
		t.Errorf("%q incorrect", "UpperSorbian")
	}
	if LanguageKenyang != 319 || LanguageKenyang.String() != "Kenyang" {
		t.Errorf("%q incorrect", "Kenyang")
	}
	if LanguageMohawk != 320 || LanguageMohawk.String() != "Mohawk" {
		t.Errorf("%q incorrect", "Mohawk")
	}
	if LanguageNko != 321 || LanguageNko.String() != "Nko" {
		t.Errorf("%q incorrect", "Nko")
	}
	if LanguagePrussian != 322 || LanguagePrussian.String() != "Prussian" {
		t.Errorf("%q incorrect", "Prussian")
	}
	if LanguageKiche != 323 || LanguageKiche.String() != "Kiche" {
		t.Errorf("%q incorrect", "Kiche")
	}
	if LanguageSouthernSami != 324 || LanguageSouthernSami.String() != "SouthernSami" {
		t.Errorf("%q incorrect", "SouthernSami")
	}
	if LanguageLuleSami != 325 || LanguageLuleSami.String() != "LuleSami" {
		t.Errorf("%q incorrect", "LuleSami")
	}
	if LanguageInariSami != 326 || LanguageInariSami.String() != "InariSami" {
		t.Errorf("%q incorrect", "InariSami")
	}
	if LanguageSkoltSami != 327 || LanguageSkoltSami.String() != "SkoltSami" {
		t.Errorf("%q incorrect", "SkoltSami")
	}
	if LanguageWarlpiri != 328 || LanguageWarlpiri.String() != "Warlpiri" {
		t.Errorf("%q incorrect", "Warlpiri")
	}
	if LanguageManichaeanMiddlePersian != 329 || LanguageManichaeanMiddlePersian.String() != "ManichaeanMiddlePersian" {
		t.Errorf("%q incorrect", "ManichaeanMiddlePersian")
	}
	if LanguageMende != 330 || LanguageMende.String() != "Mende" {
		t.Errorf("%q incorrect", "Mende")
	}
	if LanguageAncientNorthArabian != 331 || LanguageAncientNorthArabian.String() != "AncientNorthArabian" {
		t.Errorf("%q incorrect", "AncientNorthArabian")
	}
	if LanguageLinearA != 332 || LanguageLinearA.String() != "LinearA" {
		t.Errorf("%q incorrect", "LinearA")
	}
	if LanguageHmongNjua != 333 || LanguageHmongNjua.String() != "HmongNjua" {
		t.Errorf("%q incorrect", "HmongNjua")
	}
	if LanguageHo != 334 || LanguageHo.String() != "Ho" {
		t.Errorf("%q incorrect", "Ho")
	}
	if LanguageLezghian != 335 || LanguageLezghian.String() != "Lezghian" {
		t.Errorf("%q incorrect", "Lezghian")
	}
	if LanguageBassa != 336 || LanguageBassa.String() != "Bassa" {
		t.Errorf("%q incorrect", "Bassa")
	}
	if LanguageMono != 337 || LanguageMono.String() != "Mono" {
		t.Errorf("%q incorrect", "Mono")
	}
	if LanguageTedimChin != 338 || LanguageTedimChin.String() != "TedimChin" {
		t.Errorf("%q incorrect", "TedimChin")
	}
	if LanguageMaithili != 339 || LanguageMaithili.String() != "Maithili" {
		t.Errorf("%q incorrect", "Maithili")
	}
	if LanguageAhom != 340 || LanguageAhom.String() != "Ahom" {
		t.Errorf("%q incorrect", "Ahom")
	}
	if LanguageAmericanSignLanguage != 341 || LanguageAmericanSignLanguage.String() != "AmericanSignLanguage" {
		t.Errorf("%q incorrect", "AmericanSignLanguage")
	}
	if LanguageArdhamagadhiPrakrit != 342 || LanguageArdhamagadhiPrakrit.String() != "ArdhamagadhiPrakrit" {
		t.Errorf("%q incorrect", "ArdhamagadhiPrakrit")
	}
	if LanguageBhojpuri != 343 || LanguageBhojpuri.String() != "Bhojpuri" {
		t.Errorf("%q incorrect", "Bhojpuri")
	}
	if LanguageHieroglyphicLuwian != 344 || LanguageHieroglyphicLuwian.String() != "HieroglyphicLuwian" {
		t.Errorf("%q incorrect", "HieroglyphicLuwian")
	}
	if LanguageLiteraryChinese != 345 || LanguageLiteraryChinese.String() != "LiteraryChinese" {
		t.Errorf("%q incorrect", "LiteraryChinese")
	}
	if LanguageMazanderani != 346 || LanguageMazanderani.String() != "Mazanderani" {
		t.Errorf("%q incorrect", "Mazanderani")
	}
	if LanguageMru != 347 || LanguageMru.String() != "Mru" {
		t.Errorf("%q incorrect", "Mru")
	}
	if LanguageNewari != 348 || LanguageNewari.String() != "Newari" {
		t.Errorf("%q incorrect", "Newari")
	}
	if LanguageNorthernLuri != 349 || LanguageNorthernLuri.String() != "NorthernLuri" {
		t.Errorf("%q incorrect", "NorthernLuri")
	}
	if LanguagePalauan != 350 || LanguagePalauan.String() != "Palauan" {
		t.Errorf("%q incorrect", "Palauan")
	}
	if LanguagePapiamento != 351 || LanguagePapiamento.String() != "Papiamento" {
		t.Errorf("%q incorrect", "Papiamento")
	}
	if LanguageSaraiki != 352 || LanguageSaraiki.String() != "Saraiki" {
		t.Errorf("%q incorrect", "Saraiki")
	}
	if LanguageTokelauLanguage != 353 || LanguageTokelauLanguage.String() != "TokelauLanguage" {
		t.Errorf("%q incorrect", "TokelauLanguage")
	}
	if LanguageTokPisin != 354 || LanguageTokPisin.String() != "TokPisin" {
		t.Errorf("%q incorrect", "TokPisin")
	}
	if LanguageTuvaluLanguage != 355 || LanguageTuvaluLanguage.String() != "TuvaluLanguage" {
		t.Errorf("%q incorrect", "TuvaluLanguage")
	}
	if LanguageUncodedLanguages != 356 || LanguageUncodedLanguages.String() != "UncodedLanguages" {
		t.Errorf("%q incorrect", "UncodedLanguages")
	}
	if LanguageCantonese != 357 || LanguageCantonese.String() != "Cantonese" {
		t.Errorf("%q incorrect", "Cantonese")
	}
	if LanguageOsage != 358 || LanguageOsage.String() != "Osage" {
		t.Errorf("%q incorrect", "Osage")
	}
	if LanguageTangut != 359 || LanguageTangut.String() != "Tangut" {
		t.Errorf("%q incorrect", "Tangut")
	}
	if LanguageIdo != 360 || LanguageIdo.String() != "Ido" {
		t.Errorf("%q incorrect", "Ido")
	}
	if LanguageLojban != 361 || LanguageLojban.String() != "Lojban" {
		t.Errorf("%q incorrect", "Lojban")
	}
	if LanguageSicilian != 362 || LanguageSicilian.String() != "Sicilian" {
		t.Errorf("%q incorrect", "Sicilian")
	}
	if LanguageSouthernKurdish != 363 || LanguageSouthernKurdish.String() != "SouthernKurdish" {
		t.Errorf("%q incorrect", "SouthernKurdish")
	}
	if LanguageLastLanguage != 364 || LanguageLastLanguage.String() != "WesternBalochi" {
		t.Errorf("%q incorrect", "LastLanguage")
	}
	if LanguageWesternBalochi != 364 || LanguageWesternBalochi.String() != "WesternBalochi" {
		t.Errorf("%q incorrect", "WesternBalochi")
	}
}

func TestCountry(t *testing.T) {
	if CountryAnyCountry != 0 || CountryAnyCountry.String() != "AnyCountry" {
		t.Errorf("%q incorrect", "AnyCountry")
	}
	if CountryAfghanistan != 1 || CountryAfghanistan.String() != "Afghanistan" {
		t.Errorf("%q incorrect", "Afghanistan")
	}
	if CountryAlbania != 2 || CountryAlbania.String() != "Albania" {
		t.Errorf("%q incorrect", "Albania")
	}
	if CountryAlgeria != 3 || CountryAlgeria.String() != "Algeria" {
		t.Errorf("%q incorrect", "Algeria")
	}
	if CountryAmericanSamoa != 4 || CountryAmericanSamoa.String() != "AmericanSamoa" {
		t.Errorf("%q incorrect", "AmericanSamoa")
	}
	if CountryAndorra != 5 || CountryAndorra.String() != "Andorra" {
		t.Errorf("%q incorrect", "Andorra")
	}
	if CountryAngola != 6 || CountryAngola.String() != "Angola" {
		t.Errorf("%q incorrect", "Angola")
	}
	if CountryAnguilla != 7 || CountryAnguilla.String() != "Anguilla" {
		t.Errorf("%q incorrect", "Anguilla")
	}
	if CountryAntarctica != 8 || CountryAntarctica.String() != "Antarctica" {
		t.Errorf("%q incorrect", "Antarctica")
	}
	if CountryAntiguaAndBarbuda != 9 || CountryAntiguaAndBarbuda.String() != "AntiguaAndBarbuda" {
		t.Errorf("%q incorrect", "AntiguaAndBarbuda")
	}
	if CountryArgentina != 10 || CountryArgentina.String() != "Argentina" {
		t.Errorf("%q incorrect", "Argentina")
	}
	if CountryArmenia != 11 || CountryArmenia.String() != "Armenia" {
		t.Errorf("%q incorrect", "Armenia")
	}
	if CountryAruba != 12 || CountryAruba.String() != "Aruba" {
		t.Errorf("%q incorrect", "Aruba")
	}
	if CountryAustralia != 13 || CountryAustralia.String() != "Australia" {
		t.Errorf("%q incorrect", "Australia")
	}
	if CountryAustria != 14 || CountryAustria.String() != "Austria" {
		t.Errorf("%q incorrect", "Austria")
	}
	if CountryAzerbaijan != 15 || CountryAzerbaijan.String() != "Azerbaijan" {
		t.Errorf("%q incorrect", "Azerbaijan")
	}
	if CountryBahamas != 16 || CountryBahamas.String() != "Bahamas" {
		t.Errorf("%q incorrect", "Bahamas")
	}
	if CountryBahrain != 17 || CountryBahrain.String() != "Bahrain" {
		t.Errorf("%q incorrect", "Bahrain")
	}
	if CountryBangladesh != 18 || CountryBangladesh.String() != "Bangladesh" {
		t.Errorf("%q incorrect", "Bangladesh")
	}
	if CountryBarbados != 19 || CountryBarbados.String() != "Barbados" {
		t.Errorf("%q incorrect", "Barbados")
	}
	if CountryBelarus != 20 || CountryBelarus.String() != "Belarus" {
		t.Errorf("%q incorrect", "Belarus")
	}
	if CountryBelgium != 21 || CountryBelgium.String() != "Belgium" {
		t.Errorf("%q incorrect", "Belgium")
	}
	if CountryBelize != 22 || CountryBelize.String() != "Belize" {
		t.Errorf("%q incorrect", "Belize")
	}
	if CountryBenin != 23 || CountryBenin.String() != "Benin" {
		t.Errorf("%q incorrect", "Benin")
	}
	if CountryBermuda != 24 || CountryBermuda.String() != "Bermuda" {
		t.Errorf("%q incorrect", "Bermuda")
	}
	if CountryBhutan != 25 || CountryBhutan.String() != "Bhutan" {
		t.Errorf("%q incorrect", "Bhutan")
	}
	if CountryBolivia != 26 || CountryBolivia.String() != "Bolivia" {
		t.Errorf("%q incorrect", "Bolivia")
	}
	if CountryBosniaAndHerzegowina != 27 || CountryBosniaAndHerzegowina.String() != "BosniaAndHerzegowina" {
		t.Errorf("%q incorrect", "BosniaAndHerzegowina")
	}
	if CountryBotswana != 28 || CountryBotswana.String() != "Botswana" {
		t.Errorf("%q incorrect", "Botswana")
	}
	if CountryBouvetIsland != 29 || CountryBouvetIsland.String() != "BouvetIsland" {
		t.Errorf("%q incorrect", "BouvetIsland")
	}
	if CountryBrazil != 30 || CountryBrazil.String() != "Brazil" {
		t.Errorf("%q incorrect", "Brazil")
	}
	if CountryBritishIndianOceanTerritory != 31 || CountryBritishIndianOceanTerritory.String() != "BritishIndianOceanTerritory" {
		t.Errorf("%q incorrect", "BritishIndianOceanTerritory")
	}
	if CountryBrunei != 32 || CountryBrunei.String() != "Brunei" {
		t.Errorf("%q incorrect", "Brunei")
	}
	if CountryBulgaria != 33 || CountryBulgaria.String() != "Bulgaria" {
		t.Errorf("%q incorrect", "Bulgaria")
	}
	if CountryBurkinaFaso != 34 || CountryBurkinaFaso.String() != "BurkinaFaso" {
		t.Errorf("%q incorrect", "BurkinaFaso")
	}
	if CountryBurundi != 35 || CountryBurundi.String() != "Burundi" {
		t.Errorf("%q incorrect", "Burundi")
	}
	if CountryCambodia != 36 || CountryCambodia.String() != "Cambodia" {
		t.Errorf("%q incorrect", "Cambodia")
	}
	if CountryCameroon != 37 || CountryCameroon.String() != "Cameroon" {
		t.Errorf("%q incorrect", "Cameroon")
	}
	if CountryCanada != 38 || CountryCanada.String() != "Canada" {
		t.Errorf("%q incorrect", "Canada")
	}
	if CountryCapeVerde != 39 || CountryCapeVerde.String() != "CapeVerde" {
		t.Errorf("%q incorrect", "CapeVerde")
	}
	if CountryCaymanIslands != 40 || CountryCaymanIslands.String() != "CaymanIslands" {
		t.Errorf("%q incorrect", "CaymanIslands")
	}
	if CountryCentralAfricanRepublic != 41 || CountryCentralAfricanRepublic.String() != "CentralAfricanRepublic" {
		t.Errorf("%q incorrect", "CentralAfricanRepublic")
	}
	if CountryChad != 42 || CountryChad.String() != "Chad" {
		t.Errorf("%q incorrect", "Chad")
	}
	if CountryChile != 43 || CountryChile.String() != "Chile" {
		t.Errorf("%q incorrect", "Chile")
	}
	if CountryChina != 44 || CountryChina.String() != "China" {
		t.Errorf("%q incorrect", "China")
	}
	if CountryChristmasIsland != 45 || CountryChristmasIsland.String() != "ChristmasIsland" {
		t.Errorf("%q incorrect", "ChristmasIsland")
	}
	if CountryCocosIslands != 46 || CountryCocosIslands.String() != "CocosIslands" {
		t.Errorf("%q incorrect", "CocosIslands")
	}
	if CountryColombia != 47 || CountryColombia.String() != "Colombia" {
		t.Errorf("%q incorrect", "Colombia")
	}
	if CountryComoros != 48 || CountryComoros.String() != "Comoros" {
		t.Errorf("%q incorrect", "Comoros")
	}
	if CountryCongoKinshasa != 49 || CountryCongoKinshasa.String() != "CongoKinshasa" {
		t.Errorf("%q incorrect", "CongoKinshasa")
	}
	if CountryDemocraticRepublicOfCongo != 49 || CountryDemocraticRepublicOfCongo.String() != "CongoKinshasa" {
		t.Errorf("%q incorrect", "DemocraticRepublicOfCongo")
	}
	if CountryCongoBrazzaville != 50 || CountryCongoBrazzaville.String() != "CongoBrazzaville" {
		t.Errorf("%q incorrect", "CongoBrazzaville")
	}
	if CountryPeoplesRepublicOfCongo != 50 || CountryPeoplesRepublicOfCongo.String() != "CongoBrazzaville" {
		t.Errorf("%q incorrect", "PeoplesRepublicOfCongo")
	}
	if CountryCookIslands != 51 || CountryCookIslands.String() != "CookIslands" {
		t.Errorf("%q incorrect", "CookIslands")
	}
	if CountryCostaRica != 52 || CountryCostaRica.String() != "CostaRica" {
		t.Errorf("%q incorrect", "CostaRica")
	}
	if CountryIvoryCoast != 53 || CountryIvoryCoast.String() != "IvoryCoast" {
		t.Errorf("%q incorrect", "IvoryCoast")
	}
	if CountryCroatia != 54 || CountryCroatia.String() != "Croatia" {
		t.Errorf("%q incorrect", "Croatia")
	}
	if CountryCuba != 55 || CountryCuba.String() != "Cuba" {
		t.Errorf("%q incorrect", "Cuba")
	}
	if CountryCyprus != 56 || CountryCyprus.String() != "Cyprus" {
		t.Errorf("%q incorrect", "Cyprus")
	}
	if CountryCzechRepublic != 57 || CountryCzechRepublic.String() != "CzechRepublic" {
		t.Errorf("%q incorrect", "CzechRepublic")
	}
	if CountryDenmark != 58 || CountryDenmark.String() != "Denmark" {
		t.Errorf("%q incorrect", "Denmark")
	}
	if CountryDjibouti != 59 || CountryDjibouti.String() != "Djibouti" {
		t.Errorf("%q incorrect", "Djibouti")
	}
	if CountryDominica != 60 || CountryDominica.String() != "Dominica" {
		t.Errorf("%q incorrect", "Dominica")
	}
	if CountryDominicanRepublic != 61 || CountryDominicanRepublic.String() != "DominicanRepublic" {
		t.Errorf("%q incorrect", "DominicanRepublic")
	}
	if CountryEastTimor != 62 || CountryEastTimor.String() != "EastTimor" {
		t.Errorf("%q incorrect", "EastTimor")
	}
	if CountryEcuador != 63 || CountryEcuador.String() != "Ecuador" {
		t.Errorf("%q incorrect", "Ecuador")
	}
	if CountryEgypt != 64 || CountryEgypt.String() != "Egypt" {
		t.Errorf("%q incorrect", "Egypt")
	}
	if CountryElSalvador != 65 || CountryElSalvador.String() != "ElSalvador" {
		t.Errorf("%q incorrect", "ElSalvador")
	}
	if CountryEquatorialGuinea != 66 || CountryEquatorialGuinea.String() != "EquatorialGuinea" {
		t.Errorf("%q incorrect", "EquatorialGuinea")
	}
	if CountryEritrea != 67 || CountryEritrea.String() != "Eritrea" {
		t.Errorf("%q incorrect", "Eritrea")
	}
	if CountryEstonia != 68 || CountryEstonia.String() != "Estonia" {
		t.Errorf("%q incorrect", "Estonia")
	}
	if CountryEthiopia != 69 || CountryEthiopia.String() != "Ethiopia" {
		t.Errorf("%q incorrect", "Ethiopia")
	}
	if CountryFalklandIslands != 70 || CountryFalklandIslands.String() != "FalklandIslands" {
		t.Errorf("%q incorrect", "FalklandIslands")
	}
	if CountryFaroeIslands != 71 || CountryFaroeIslands.String() != "FaroeIslands" {
		t.Errorf("%q incorrect", "FaroeIslands")
	}
	if CountryFiji != 72 || CountryFiji.String() != "Fiji" {
		t.Errorf("%q incorrect", "Fiji")
	}
	if CountryFinland != 73 || CountryFinland.String() != "Finland" {
		t.Errorf("%q incorrect", "Finland")
	}
	if CountryFrance != 74 || CountryFrance.String() != "France" {
		t.Errorf("%q incorrect", "France")
	}
	if CountryGuernsey != 75 || CountryGuernsey.String() != "Guernsey" {
		t.Errorf("%q incorrect", "Guernsey")
	}
	if CountryFrenchGuiana != 76 || CountryFrenchGuiana.String() != "FrenchGuiana" {
		t.Errorf("%q incorrect", "FrenchGuiana")
	}
	if CountryFrenchPolynesia != 77 || CountryFrenchPolynesia.String() != "FrenchPolynesia" {
		t.Errorf("%q incorrect", "FrenchPolynesia")
	}
	if CountryFrenchSouthernTerritories != 78 || CountryFrenchSouthernTerritories.String() != "FrenchSouthernTerritories" {
		t.Errorf("%q incorrect", "FrenchSouthernTerritories")
	}
	if CountryGabon != 79 || CountryGabon.String() != "Gabon" {
		t.Errorf("%q incorrect", "Gabon")
	}
	if CountryGambia != 80 || CountryGambia.String() != "Gambia" {
		t.Errorf("%q incorrect", "Gambia")
	}
	if CountryGeorgia != 81 || CountryGeorgia.String() != "Georgia" {
		t.Errorf("%q incorrect", "Georgia")
	}
	if CountryGermany != 82 || CountryGermany.String() != "Germany" {
		t.Errorf("%q incorrect", "Germany")
	}
	if CountryGhana != 83 || CountryGhana.String() != "Ghana" {
		t.Errorf("%q incorrect", "Ghana")
	}
	if CountryGibraltar != 84 || CountryGibraltar.String() != "Gibraltar" {
		t.Errorf("%q incorrect", "Gibraltar")
	}
	if CountryGreece != 85 || CountryGreece.String() != "Greece" {
		t.Errorf("%q incorrect", "Greece")
	}
	if CountryGreenland != 86 || CountryGreenland.String() != "Greenland" {
		t.Errorf("%q incorrect", "Greenland")
	}
	if CountryGrenada != 87 || CountryGrenada.String() != "Grenada" {
		t.Errorf("%q incorrect", "Grenada")
	}
	if CountryGuadeloupe != 88 || CountryGuadeloupe.String() != "Guadeloupe" {
		t.Errorf("%q incorrect", "Guadeloupe")
	}
	if CountryGuam != 89 || CountryGuam.String() != "Guam" {
		t.Errorf("%q incorrect", "Guam")
	}
	if CountryGuatemala != 90 || CountryGuatemala.String() != "Guatemala" {
		t.Errorf("%q incorrect", "Guatemala")
	}
	if CountryGuinea != 91 || CountryGuinea.String() != "Guinea" {
		t.Errorf("%q incorrect", "Guinea")
	}
	if CountryGuineaBissau != 92 || CountryGuineaBissau.String() != "GuineaBissau" {
		t.Errorf("%q incorrect", "GuineaBissau")
	}
	if CountryGuyana != 93 || CountryGuyana.String() != "Guyana" {
		t.Errorf("%q incorrect", "Guyana")
	}
	if CountryHaiti != 94 || CountryHaiti.String() != "Haiti" {
		t.Errorf("%q incorrect", "Haiti")
	}
	if CountryHeardAndMcDonaldIslands != 95 || CountryHeardAndMcDonaldIslands.String() != "HeardAndMcDonaldIslands" {
		t.Errorf("%q incorrect", "HeardAndMcDonaldIslands")
	}
	if CountryHonduras != 96 || CountryHonduras.String() != "Honduras" {
		t.Errorf("%q incorrect", "Honduras")
	}
	if CountryHongKong != 97 || CountryHongKong.String() != "HongKong" {
		t.Errorf("%q incorrect", "HongKong")
	}
	if CountryHungary != 98 || CountryHungary.String() != "Hungary" {
		t.Errorf("%q incorrect", "Hungary")
	}
	if CountryIceland != 99 || CountryIceland.String() != "Iceland" {
		t.Errorf("%q incorrect", "Iceland")
	}
	if CountryIndia != 100 || CountryIndia.String() != "India" {
		t.Errorf("%q incorrect", "India")
	}
	if CountryIndonesia != 101 || CountryIndonesia.String() != "Indonesia" {
		t.Errorf("%q incorrect", "Indonesia")
	}
	if CountryIran != 102 || CountryIran.String() != "Iran" {
		t.Errorf("%q incorrect", "Iran")
	}
	if CountryIraq != 103 || CountryIraq.String() != "Iraq" {
		t.Errorf("%q incorrect", "Iraq")
	}
	if CountryIreland != 104 || CountryIreland.String() != "Ireland" {
		t.Errorf("%q incorrect", "Ireland")
	}
	if CountryIsrael != 105 || CountryIsrael.String() != "Israel" {
		t.Errorf("%q incorrect", "Israel")
	}
	if CountryItaly != 106 || CountryItaly.String() != "Italy" {
		t.Errorf("%q incorrect", "Italy")
	}
	if CountryJamaica != 107 || CountryJamaica.String() != "Jamaica" {
		t.Errorf("%q incorrect", "Jamaica")
	}
	if CountryJapan != 108 || CountryJapan.String() != "Japan" {
		t.Errorf("%q incorrect", "Japan")
	}
	if CountryJordan != 109 || CountryJordan.String() != "Jordan" {
		t.Errorf("%q incorrect", "Jordan")
	}
	if CountryKazakhstan != 110 || CountryKazakhstan.String() != "Kazakhstan" {
		t.Errorf("%q incorrect", "Kazakhstan")
	}
	if CountryKenya != 111 || CountryKenya.String() != "Kenya" {
		t.Errorf("%q incorrect", "Kenya")
	}
	if CountryKiribati != 112 || CountryKiribati.String() != "Kiribati" {
		t.Errorf("%q incorrect", "Kiribati")
	}
	if CountryNorthKorea != 113 || CountryNorthKorea.String() != "NorthKorea" {
		t.Errorf("%q incorrect", "NorthKorea")
	}
	if CountryDemocraticRepublicOfKorea != 113 || CountryDemocraticRepublicOfKorea.String() != "NorthKorea" {
		t.Errorf("%q incorrect", "DemocraticRepublicOfKorea")
	}
	if CountrySouthKorea != 114 || CountrySouthKorea.String() != "SouthKorea" {
		t.Errorf("%q incorrect", "SouthKorea")
	}
	if CountryRepublicOfKorea != 114 || CountryRepublicOfKorea.String() != "SouthKorea" {
		t.Errorf("%q incorrect", "RepublicOfKorea")
	}
	if CountryKuwait != 115 || CountryKuwait.String() != "Kuwait" {
		t.Errorf("%q incorrect", "Kuwait")
	}
	if CountryKyrgyzstan != 116 || CountryKyrgyzstan.String() != "Kyrgyzstan" {
		t.Errorf("%q incorrect", "Kyrgyzstan")
	}
	if CountryLaos != 117 || CountryLaos.String() != "Laos" {
		t.Errorf("%q incorrect", "Laos")
	}
	if CountryLatvia != 118 || CountryLatvia.String() != "Latvia" {
		t.Errorf("%q incorrect", "Latvia")
	}
	if CountryLebanon != 119 || CountryLebanon.String() != "Lebanon" {
		t.Errorf("%q incorrect", "Lebanon")
	}
	if CountryLesotho != 120 || CountryLesotho.String() != "Lesotho" {
		t.Errorf("%q incorrect", "Lesotho")
	}
	if CountryLiberia != 121 || CountryLiberia.String() != "Liberia" {
		t.Errorf("%q incorrect", "Liberia")
	}
	if CountryLibya != 122 || CountryLibya.String() != "Libya" {
		t.Errorf("%q incorrect", "Libya")
	}
	if CountryLiechtenstein != 123 || CountryLiechtenstein.String() != "Liechtenstein" {
		t.Errorf("%q incorrect", "Liechtenstein")
	}
	if CountryLithuania != 124 || CountryLithuania.String() != "Lithuania" {
		t.Errorf("%q incorrect", "Lithuania")
	}
	if CountryLuxembourg != 125 || CountryLuxembourg.String() != "Luxembourg" {
		t.Errorf("%q incorrect", "Luxembourg")
	}
	if CountryMacau != 126 || CountryMacau.String() != "Macau" {
		t.Errorf("%q incorrect", "Macau")
	}
	if CountryMacedonia != 127 || CountryMacedonia.String() != "Macedonia" {
		t.Errorf("%q incorrect", "Macedonia")
	}
	if CountryMadagascar != 128 || CountryMadagascar.String() != "Madagascar" {
		t.Errorf("%q incorrect", "Madagascar")
	}
	if CountryMalawi != 129 || CountryMalawi.String() != "Malawi" {
		t.Errorf("%q incorrect", "Malawi")
	}
	if CountryMalaysia != 130 || CountryMalaysia.String() != "Malaysia" {
		t.Errorf("%q incorrect", "Malaysia")
	}
	if CountryMaldives != 131 || CountryMaldives.String() != "Maldives" {
		t.Errorf("%q incorrect", "Maldives")
	}
	if CountryMali != 132 || CountryMali.String() != "Mali" {
		t.Errorf("%q incorrect", "Mali")
	}
	if CountryMalta != 133 || CountryMalta.String() != "Malta" {
		t.Errorf("%q incorrect", "Malta")
	}
	if CountryMarshallIslands != 134 || CountryMarshallIslands.String() != "MarshallIslands" {
		t.Errorf("%q incorrect", "MarshallIslands")
	}
	if CountryMartinique != 135 || CountryMartinique.String() != "Martinique" {
		t.Errorf("%q incorrect", "Martinique")
	}
	if CountryMauritania != 136 || CountryMauritania.String() != "Mauritania" {
		t.Errorf("%q incorrect", "Mauritania")
	}
	if CountryMauritius != 137 || CountryMauritius.String() != "Mauritius" {
		t.Errorf("%q incorrect", "Mauritius")
	}
	if CountryMayotte != 138 || CountryMayotte.String() != "Mayotte" {
		t.Errorf("%q incorrect", "Mayotte")
	}
	if CountryMexico != 139 || CountryMexico.String() != "Mexico" {
		t.Errorf("%q incorrect", "Mexico")
	}
	if CountryMicronesia != 140 || CountryMicronesia.String() != "Micronesia" {
		t.Errorf("%q incorrect", "Micronesia")
	}
	if CountryMoldova != 141 || CountryMoldova.String() != "Moldova" {
		t.Errorf("%q incorrect", "Moldova")
	}
	if CountryMonaco != 142 || CountryMonaco.String() != "Monaco" {
		t.Errorf("%q incorrect", "Monaco")
	}
	if CountryMongolia != 143 || CountryMongolia.String() != "Mongolia" {
		t.Errorf("%q incorrect", "Mongolia")
	}
	if CountryMontserrat != 144 || CountryMontserrat.String() != "Montserrat" {
		t.Errorf("%q incorrect", "Montserrat")
	}
	if CountryMorocco != 145 || CountryMorocco.String() != "Morocco" {
		t.Errorf("%q incorrect", "Morocco")
	}
	if CountryMozambique != 146 || CountryMozambique.String() != "Mozambique" {
		t.Errorf("%q incorrect", "Mozambique")
	}
	if CountryMyanmar != 147 || CountryMyanmar.String() != "Myanmar" {
		t.Errorf("%q incorrect", "Myanmar")
	}
	if CountryNamibia != 148 || CountryNamibia.String() != "Namibia" {
		t.Errorf("%q incorrect", "Namibia")
	}
	if CountryNauruCountry != 149 || CountryNauruCountry.String() != "NauruCountry" {
		t.Errorf("%q incorrect", "NauruCountry")
	}
	if CountryNepal != 150 || CountryNepal.String() != "Nepal" {
		t.Errorf("%q incorrect", "Nepal")
	}
	if CountryNetherlands != 151 || CountryNetherlands.String() != "Netherlands" {
		t.Errorf("%q incorrect", "Netherlands")
	}
	if CountryCuraSao != 152 || CountryCuraSao.String() != "CuraSao" {
		t.Errorf("%q incorrect", "CuraSao")
	}
	if CountryNewCaledonia != 153 || CountryNewCaledonia.String() != "NewCaledonia" {
		t.Errorf("%q incorrect", "NewCaledonia")
	}
	if CountryNewZealand != 154 || CountryNewZealand.String() != "NewZealand" {
		t.Errorf("%q incorrect", "NewZealand")
	}
	if CountryNicaragua != 155 || CountryNicaragua.String() != "Nicaragua" {
		t.Errorf("%q incorrect", "Nicaragua")
	}
	if CountryNiger != 156 || CountryNiger.String() != "Niger" {
		t.Errorf("%q incorrect", "Niger")
	}
	if CountryNigeria != 157 || CountryNigeria.String() != "Nigeria" {
		t.Errorf("%q incorrect", "Nigeria")
	}
	if CountryNiue != 158 || CountryNiue.String() != "Niue" {
		t.Errorf("%q incorrect", "Niue")
	}
	if CountryNorfolkIsland != 159 || CountryNorfolkIsland.String() != "NorfolkIsland" {
		t.Errorf("%q incorrect", "NorfolkIsland")
	}
	if CountryNorthernMarianaIslands != 160 || CountryNorthernMarianaIslands.String() != "NorthernMarianaIslands" {
		t.Errorf("%q incorrect", "NorthernMarianaIslands")
	}
	if CountryNorway != 161 || CountryNorway.String() != "Norway" {
		t.Errorf("%q incorrect", "Norway")
	}
	if CountryOman != 162 || CountryOman.String() != "Oman" {
		t.Errorf("%q incorrect", "Oman")
	}
	if CountryPakistan != 163 || CountryPakistan.String() != "Pakistan" {
		t.Errorf("%q incorrect", "Pakistan")
	}
	if CountryPalau != 164 || CountryPalau.String() != "Palau" {
		t.Errorf("%q incorrect", "Palau")
	}
	if CountryPalestinianTerritories != 165 || CountryPalestinianTerritories.String() != "PalestinianTerritories" {
		t.Errorf("%q incorrect", "PalestinianTerritories")
	}
	if CountryPanama != 166 || CountryPanama.String() != "Panama" {
		t.Errorf("%q incorrect", "Panama")
	}
	if CountryPapuaNewGuinea != 167 || CountryPapuaNewGuinea.String() != "PapuaNewGuinea" {
		t.Errorf("%q incorrect", "PapuaNewGuinea")
	}
	if CountryParaguay != 168 || CountryParaguay.String() != "Paraguay" {
		t.Errorf("%q incorrect", "Paraguay")
	}
	if CountryPeru != 169 || CountryPeru.String() != "Peru" {
		t.Errorf("%q incorrect", "Peru")
	}
	if CountryPhilippines != 170 || CountryPhilippines.String() != "Philippines" {
		t.Errorf("%q incorrect", "Philippines")
	}
	if CountryPitcairn != 171 || CountryPitcairn.String() != "Pitcairn" {
		t.Errorf("%q incorrect", "Pitcairn")
	}
	if CountryPoland != 172 || CountryPoland.String() != "Poland" {
		t.Errorf("%q incorrect", "Poland")
	}
	if CountryPortugal != 173 || CountryPortugal.String() != "Portugal" {
		t.Errorf("%q incorrect", "Portugal")
	}
	if CountryPuertoRico != 174 || CountryPuertoRico.String() != "PuertoRico" {
		t.Errorf("%q incorrect", "PuertoRico")
	}
	if CountryQatar != 175 || CountryQatar.String() != "Qatar" {
		t.Errorf("%q incorrect", "Qatar")
	}
	if CountryReunion != 176 || CountryReunion.String() != "Reunion" {
		t.Errorf("%q incorrect", "Reunion")
	}
	if CountryRomania != 177 || CountryRomania.String() != "Romania" {
		t.Errorf("%q incorrect", "Romania")
	}
	if CountryRussia != 178 || CountryRussia.String() != "Russia" {
		t.Errorf("%q incorrect", "Russia")
	}
	if CountryRussianFederation != 178 || CountryRussianFederation.String() != "Russia" {
		t.Errorf("%q incorrect", "RussianFederation")
	}
	if CountryRwanda != 179 || CountryRwanda.String() != "Rwanda" {
		t.Errorf("%q incorrect", "Rwanda")
	}
	if CountrySaintKittsAndNevis != 180 || CountrySaintKittsAndNevis.String() != "SaintKittsAndNevis" {
		t.Errorf("%q incorrect", "SaintKittsAndNevis")
	}
	if CountrySaintLucia != 181 || CountrySaintLucia.String() != "SaintLucia" {
		t.Errorf("%q incorrect", "SaintLucia")
	}
	if CountrySaintVincentAndTheGrenadines != 182 || CountrySaintVincentAndTheGrenadines.String() != "SaintVincentAndTheGrenadines" {
		t.Errorf("%q incorrect", "SaintVincentAndTheGrenadines")
	}
	if CountrySamoa != 183 || CountrySamoa.String() != "Samoa" {
		t.Errorf("%q incorrect", "Samoa")
	}
	if CountrySanMarino != 184 || CountrySanMarino.String() != "SanMarino" {
		t.Errorf("%q incorrect", "SanMarino")
	}
	if CountrySaoTomeAndPrincipe != 185 || CountrySaoTomeAndPrincipe.String() != "SaoTomeAndPrincipe" {
		t.Errorf("%q incorrect", "SaoTomeAndPrincipe")
	}
	if CountrySaudiArabia != 186 || CountrySaudiArabia.String() != "SaudiArabia" {
		t.Errorf("%q incorrect", "SaudiArabia")
	}
	if CountrySenegal != 187 || CountrySenegal.String() != "Senegal" {
		t.Errorf("%q incorrect", "Senegal")
	}
	if CountrySeychelles != 188 || CountrySeychelles.String() != "Seychelles" {
		t.Errorf("%q incorrect", "Seychelles")
	}
	if CountrySierraLeone != 189 || CountrySierraLeone.String() != "SierraLeone" {
		t.Errorf("%q incorrect", "SierraLeone")
	}
	if CountrySingapore != 190 || CountrySingapore.String() != "Singapore" {
		t.Errorf("%q incorrect", "Singapore")
	}
	if CountrySlovakia != 191 || CountrySlovakia.String() != "Slovakia" {
		t.Errorf("%q incorrect", "Slovakia")
	}
	if CountrySlovenia != 192 || CountrySlovenia.String() != "Slovenia" {
		t.Errorf("%q incorrect", "Slovenia")
	}
	if CountrySolomonIslands != 193 || CountrySolomonIslands.String() != "SolomonIslands" {
		t.Errorf("%q incorrect", "SolomonIslands")
	}
	if CountrySomalia != 194 || CountrySomalia.String() != "Somalia" {
		t.Errorf("%q incorrect", "Somalia")
	}
	if CountrySouthAfrica != 195 || CountrySouthAfrica.String() != "SouthAfrica" {
		t.Errorf("%q incorrect", "SouthAfrica")
	}
	if CountrySouthGeorgiaAndTheSouthSandwichIslands != 196 || CountrySouthGeorgiaAndTheSouthSandwichIslands.String() != "SouthGeorgiaAndTheSouthSandwichIslands" {
		t.Errorf("%q incorrect", "SouthGeorgiaAndTheSouthSandwichIslands")
	}
	if CountrySpain != 197 || CountrySpain.String() != "Spain" {
		t.Errorf("%q incorrect", "Spain")
	}
	if CountrySriLanka != 198 || CountrySriLanka.String() != "SriLanka" {
		t.Errorf("%q incorrect", "SriLanka")
	}
	if CountrySaintHelena != 199 || CountrySaintHelena.String() != "SaintHelena" {
		t.Errorf("%q incorrect", "SaintHelena")
	}
	if CountrySaintPierreAndMiquelon != 200 || CountrySaintPierreAndMiquelon.String() != "SaintPierreAndMiquelon" {
		t.Errorf("%q incorrect", "SaintPierreAndMiquelon")
	}
	if CountrySudan != 201 || CountrySudan.String() != "Sudan" {
		t.Errorf("%q incorrect", "Sudan")
	}
	if CountrySuriname != 202 || CountrySuriname.String() != "Suriname" {
		t.Errorf("%q incorrect", "Suriname")
	}
	if CountrySvalbardAndJanMayenIslands != 203 || CountrySvalbardAndJanMayenIslands.String() != "SvalbardAndJanMayenIslands" {
		t.Errorf("%q incorrect", "SvalbardAndJanMayenIslands")
	}
	if CountrySwaziland != 204 || CountrySwaziland.String() != "Swaziland" {
		t.Errorf("%q incorrect", "Swaziland")
	}
	if CountrySweden != 205 || CountrySweden.String() != "Sweden" {
		t.Errorf("%q incorrect", "Sweden")
	}
	if CountrySwitzerland != 206 || CountrySwitzerland.String() != "Switzerland" {
		t.Errorf("%q incorrect", "Switzerland")
	}
	if CountrySyrianArabRepublic != 207 || CountrySyrianArabRepublic.String() != "Syria" {
		t.Errorf("%q incorrect", "SyrianArabRepublic")
	}
	if CountrySyria != 207 || CountrySyria.String() != "Syria" {
		t.Errorf("%q incorrect", "Syria")
	}
	if CountryTaiwan != 208 || CountryTaiwan.String() != "Taiwan" {
		t.Errorf("%q incorrect", "Taiwan")
	}
	if CountryTajikistan != 209 || CountryTajikistan.String() != "Tajikistan" {
		t.Errorf("%q incorrect", "Tajikistan")
	}
	if CountryTanzania != 210 || CountryTanzania.String() != "Tanzania" {
		t.Errorf("%q incorrect", "Tanzania")
	}
	if CountryThailand != 211 || CountryThailand.String() != "Thailand" {
		t.Errorf("%q incorrect", "Thailand")
	}
	if CountryTogo != 212 || CountryTogo.String() != "Togo" {
		t.Errorf("%q incorrect", "Togo")
	}
	if CountryTokelau != 213 || CountryTokelau.String() != "TokelauCountry" {
		t.Errorf("%q incorrect", "Tokelau")
	}
	if CountryTokelauCountry != 213 || CountryTokelauCountry.String() != "TokelauCountry" {
		t.Errorf("%q incorrect", "TokelauCountry")
	}
	if CountryTonga != 214 || CountryTonga.String() != "Tonga" {
		t.Errorf("%q incorrect", "Tonga")
	}
	if CountryTrinidadAndTobago != 215 || CountryTrinidadAndTobago.String() != "TrinidadAndTobago" {
		t.Errorf("%q incorrect", "TrinidadAndTobago")
	}
	if CountryTunisia != 216 || CountryTunisia.String() != "Tunisia" {
		t.Errorf("%q incorrect", "Tunisia")
	}
	if CountryTurkey != 217 || CountryTurkey.String() != "Turkey" {
		t.Errorf("%q incorrect", "Turkey")
	}
	if CountryTurkmenistan != 218 || CountryTurkmenistan.String() != "Turkmenistan" {
		t.Errorf("%q incorrect", "Turkmenistan")
	}
	if CountryTurksAndCaicosIslands != 219 || CountryTurksAndCaicosIslands.String() != "TurksAndCaicosIslands" {
		t.Errorf("%q incorrect", "TurksAndCaicosIslands")
	}
	if CountryTuvalu != 220 || CountryTuvalu.String() != "TuvaluCountry" {
		t.Errorf("%q incorrect", "Tuvalu")
	}
	if CountryTuvaluCountry != 220 || CountryTuvaluCountry.String() != "TuvaluCountry" {
		t.Errorf("%q incorrect", "TuvaluCountry")
	}
	if CountryUganda != 221 || CountryUganda.String() != "Uganda" {
		t.Errorf("%q incorrect", "Uganda")
	}
	if CountryUkraine != 222 || CountryUkraine.String() != "Ukraine" {
		t.Errorf("%q incorrect", "Ukraine")
	}
	if CountryUnitedArabEmirates != 223 || CountryUnitedArabEmirates.String() != "UnitedArabEmirates" {
		t.Errorf("%q incorrect", "UnitedArabEmirates")
	}
	if CountryUnitedKingdom != 224 || CountryUnitedKingdom.String() != "UnitedKingdom" {
		t.Errorf("%q incorrect", "UnitedKingdom")
	}
	if CountryUnitedStates != 225 || CountryUnitedStates.String() != "UnitedStates" {
		t.Errorf("%q incorrect", "UnitedStates")
	}
	if CountryUnitedStatesMinorOutlyingIslands != 226 || CountryUnitedStatesMinorOutlyingIslands.String() != "UnitedStatesMinorOutlyingIslands" {
		t.Errorf("%q incorrect", "UnitedStatesMinorOutlyingIslands")
	}
	if CountryUruguay != 227 || CountryUruguay.String() != "Uruguay" {
		t.Errorf("%q incorrect", "Uruguay")
	}
	if CountryUzbekistan != 228 || CountryUzbekistan.String() != "Uzbekistan" {
		t.Errorf("%q incorrect", "Uzbekistan")
	}
	if CountryVanuatu != 229 || CountryVanuatu.String() != "Vanuatu" {
		t.Errorf("%q incorrect", "Vanuatu")
	}
	if CountryVaticanCityState != 230 || CountryVaticanCityState.String() != "VaticanCityState" {
		t.Errorf("%q incorrect", "VaticanCityState")
	}
	if CountryVenezuela != 231 || CountryVenezuela.String() != "Venezuela" {
		t.Errorf("%q incorrect", "Venezuela")
	}
	if CountryVietnam != 232 || CountryVietnam.String() != "Vietnam" {
		t.Errorf("%q incorrect", "Vietnam")
	}
	if CountryBritishVirginIslands != 233 || CountryBritishVirginIslands.String() != "BritishVirginIslands" {
		t.Errorf("%q incorrect", "BritishVirginIslands")
	}
	if CountryUnitedStatesVirginIslands != 234 || CountryUnitedStatesVirginIslands.String() != "UnitedStatesVirginIslands" {
		t.Errorf("%q incorrect", "UnitedStatesVirginIslands")
	}
	if CountryWallisAndFutunaIslands != 235 || CountryWallisAndFutunaIslands.String() != "WallisAndFutunaIslands" {
		t.Errorf("%q incorrect", "WallisAndFutunaIslands")
	}
	if CountryWesternSahara != 236 || CountryWesternSahara.String() != "WesternSahara" {
		t.Errorf("%q incorrect", "WesternSahara")
	}
	if CountryYemen != 237 || CountryYemen.String() != "Yemen" {
		t.Errorf("%q incorrect", "Yemen")
	}
	if CountryCanaryIslands != 238 || CountryCanaryIslands.String() != "CanaryIslands" {
		t.Errorf("%q incorrect", "CanaryIslands")
	}
	if CountryZambia != 239 || CountryZambia.String() != "Zambia" {
		t.Errorf("%q incorrect", "Zambia")
	}
	if CountryZimbabwe != 240 || CountryZimbabwe.String() != "Zimbabwe" {
		t.Errorf("%q incorrect", "Zimbabwe")
	}
	if CountryClippertonIsland != 241 || CountryClippertonIsland.String() != "ClippertonIsland" {
		t.Errorf("%q incorrect", "ClippertonIsland")
	}
	if CountryMontenegro != 242 || CountryMontenegro.String() != "Montenegro" {
		t.Errorf("%q incorrect", "Montenegro")
	}
	if CountrySerbia != 243 || CountrySerbia.String() != "Serbia" {
		t.Errorf("%q incorrect", "Serbia")
	}
	if CountrySaintBarthelemy != 244 || CountrySaintBarthelemy.String() != "SaintBarthelemy" {
		t.Errorf("%q incorrect", "SaintBarthelemy")
	}
	if CountrySaintMartin != 245 || CountrySaintMartin.String() != "SaintMartin" {
		t.Errorf("%q incorrect", "SaintMartin")
	}
	if CountryLatinAmerica != 246 || CountryLatinAmerica.String() != "LatinAmerica" {
		t.Errorf("%q incorrect", "LatinAmerica")
	}
	if CountryLatinAmericaAndTheCaribbean != 246 || CountryLatinAmericaAndTheCaribbean.String() != "LatinAmerica" {
		t.Errorf("%q incorrect", "LatinAmericaAndTheCaribbean")
	}
	if CountryAscensionIsland != 247 || CountryAscensionIsland.String() != "AscensionIsland" {
		t.Errorf("%q incorrect", "AscensionIsland")
	}
	if CountryAlandIslands != 248 || CountryAlandIslands.String() != "AlandIslands" {
		t.Errorf("%q incorrect", "AlandIslands")
	}
	if CountryDiegoGarcia != 249 || CountryDiegoGarcia.String() != "DiegoGarcia" {
		t.Errorf("%q incorrect", "DiegoGarcia")
	}
	if CountryCeutaAndMelilla != 250 || CountryCeutaAndMelilla.String() != "CeutaAndMelilla" {
		t.Errorf("%q incorrect", "CeutaAndMelilla")
	}
	if CountryIsleOfMan != 251 || CountryIsleOfMan.String() != "IsleOfMan" {
		t.Errorf("%q incorrect", "IsleOfMan")
	}
	if CountryJersey != 252 || CountryJersey.String() != "Jersey" {
		t.Errorf("%q incorrect", "Jersey")
	}
	if CountryTristanDaCunha != 253 || CountryTristanDaCunha.String() != "TristanDaCunha" {
		t.Errorf("%q incorrect", "TristanDaCunha")
	}
	if CountrySouthSudan != 254 || CountrySouthSudan.String() != "SouthSudan" {
		t.Errorf("%q incorrect", "SouthSudan")
	}
	if CountryBonaire != 255 || CountryBonaire.String() != "Bonaire" {
		t.Errorf("%q incorrect", "Bonaire")
	}
	if CountrySintMaarten != 256 || CountrySintMaarten.String() != "SintMaarten" {
		t.Errorf("%q incorrect", "SintMaarten")
	}
	if CountryKosovo != 257 || CountryKosovo.String() != "Kosovo" {
		t.Errorf("%q incorrect", "Kosovo")
	}
	if CountryEuropeanUnion != 258 || CountryEuropeanUnion.String() != "EuropeanUnion" {
		t.Errorf("%q incorrect", "EuropeanUnion")
	}
	if CountryOutlyingOceania != 259 || CountryOutlyingOceania.String() != "OutlyingOceania" {
		t.Errorf("%q incorrect", "OutlyingOceania")
	}
	if CountryWorld != 260 || CountryWorld.String() != "World" {
		t.Errorf("%q incorrect", "World")
	}
	if CountryEurope != 261 || CountryEurope.String() != "Europe" {
		t.Errorf("%q incorrect", "Europe")
	}
	if CountryLastCountry != 261 || CountryLastCountry.String() != "Europe" {
		t.Errorf("%q incorrect", "LastCountry")
	}
}
